//! Round 4, change 2: **user-authored parts** - the field list, the value model and the validation.
//!
//! Pure Rust, no Bevy: the form the app draws and the checks that refuse a value are the *same* code, and
//! both are unit-tested natively (see the tests at the bottom of this file).
//!
//! What is generated and what is not:
//!
//! - The **field list** is not invented here: `viz/assets/custom-fields.json` is generated by
//!   `tools/gen-custom-fields.mjs` from `../fixtures-fields.json` (the canonical field names *and their
//!   order*, per class) plus `viz/assets/fixture.json` (the type of each field, and the range = the span the
//!   bundled catalog itself records for it). One field list, one generator, one consumer: the form draws
//!   exactly the fields of the class and offers no way to add one.
//! - The **unit** of each field comes from that same generated file, from the documented suffix table in the
//!   generator (`M2` -> m2, `C` -> C, `Pa` -> Pa, ...), so the form, the hover card and the fixture's own
//!   contract field names read the same way.
//! - The **range** each field advertises is the span of the values the bundled catalog records for it. The
//!   pass has no other evidence for what is possible, so it refuses outside that span and names it. Nothing
//!   is estimated to widen it.

use serde::Deserialize;

/// How the form edits a field. One variant per *shape* the fixture's own records have.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Kind {
    /// A free-text field (`id`, `name`, `geometry`, `pressureBasis`).
    Text,
    /// A single number with a unit (most of the fixture's fields).
    Number,
    /// A two-ended number: `[lo, hi]` (`allowedSpeedRatio`).
    Range2,
    /// A list of strings (`compatibleTowerTypes`, `allowedWaterQualityClasses`, ...).
    TextList,
    /// A point table: x/y rows (`curve`, `thermal`, `pressure`, and the fill's sampled `characteristic`).
    Points,
    /// A group of named numbers (the fill's `limits`).
    Object,
}

/// One column of a point table.
#[derive(Clone, Debug, Deserialize)]
pub struct Column {
    pub key: String,
    pub unit: String,
}

/// One number inside an `Object` field.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubField {
    pub key: String,
    pub unit: String,
    /// Required sub-fields are marked in the form; optional ones may be left blank.
    #[serde(default)]
    pub required: bool,
    pub min: Option<f64>,
    pub max: Option<f64>,
}

/// A scalar that belongs to a point table rather than to the rows (`atDryAirLoadingKgM2S`).
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Companion {
    pub key: String,
    pub unit: String,
    pub min: Option<f64>,
    pub max: Option<f64>,
}

/// One field of a class, exactly as `fixtures-fields.json` names it.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Field {
    pub key: String,
    pub unit: String,
    pub kind: Kind,
    /// A required field is marked in the form and refuses an empty value.
    #[serde(default)]
    pub required: bool,
    pub min: Option<f64>,
    pub max: Option<f64>,
    /// The point table's x column must increase (the fixture's own tables are monotonic in x).
    #[serde(default)]
    pub monotonic: bool,
    /// For a `Text` field: the vocabulary the catalog records (empty = free text).
    #[serde(default)]
    pub one_of: Vec<String>,
    #[serde(default)]
    pub columns: Vec<Column>,
    #[serde(default)]
    pub sub: Vec<SubField>,
    pub companion: Option<Companion>,
    /// Where this field's entry in the list comes from - printed in the form's footer.
    #[serde(default)]
    pub from: String,
    /// A short note the form shows beside the control (e.g. the unit's own convention).
    #[serde(default)]
    pub note: String,
}

/// One class's field list.
#[derive(Clone, Debug, Deserialize)]
pub struct ClassSpec {
    pub class: String,
    pub title: String,
    pub fields: Vec<Field>,
}

/// The generated descriptor: four classes, each with the fields of its class.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Fields {
    pub generated_by: String,
    pub field_list_source: String,
    pub value_source: String,
    pub note: String,
    pub classes: Vec<ClassSpec>,
}

impl Fields {
    pub fn from_json(text: &str) -> Result<Self, String> {
        serde_json::from_str(text).map_err(|e| format!("custom-fields.json: {e}"))
    }
    pub fn class(&self, slug: &str) -> Option<&ClassSpec> {
        self.classes.iter().find(|c| c.class == slug)
    }
    pub fn field_count(&self) -> usize {
        self.classes.iter().map(|c| c.fields.len()).sum()
    }
}

// ---------------------------------------------------------------------------------- the value model

/// A value the user typed, already parsed. `Number`/`Range2`/`Object` hold numbers because the fixture's
/// own schema holds numbers; the parse step is what turns the text into them.
#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    Text(String),
    Number(f64),
    Range2(f64, f64),
    TextList(Vec<String>),
    Points(Vec<Vec<f64>>),
    Object(Vec<(String, f64)>),
}

impl Value {
    /// How the value reads in a one-line summary (the form's footer and the hover card).
    pub fn summary(&self) -> String {
        match self {
            Value::Text(s) => s.clone(),
            Value::Number(n) => trim(*n),
            Value::Range2(a, b) => format!("{} .. {}", trim(*a), trim(*b)),
            Value::TextList(v) => v.join(", "),
            Value::Points(p) => format!("{} point(s)", p.len()),
            Value::Object(o) => o
                .iter()
                .map(|(k, v)| format!("{k} {}", trim(*v)))
                .collect::<Vec<_>>()
                .join(" · "),
        }
    }
    pub fn as_number(&self) -> Option<f64> {
        match self {
            Value::Number(n) => Some(*n),
            _ => None,
        }
    }
    pub fn as_text(&self) -> Option<&str> {
        match self {
            Value::Text(s) => Some(s.as_str()),
            _ => None,
        }
    }
    pub fn as_range2(&self) -> Option<(f64, f64)> {
        match self {
            Value::Range2(a, b) => Some((*a, *b)),
            _ => None,
        }
    }
    pub fn as_list(&self) -> Option<&[String]> {
        match self {
            Value::TextList(v) => Some(v.as_slice()),
            _ => None,
        }
    }
    pub fn as_points(&self) -> Option<&[Vec<f64>]> {
        match self {
            Value::Points(p) => Some(p.as_slice()),
            _ => None,
        }
    }
    pub fn as_object(&self) -> Option<&[(String, f64)]> {
        match self {
            Value::Object(o) => Some(o.as_slice()),
            _ => None,
        }
    }
}

/// The form's raw text: one string per scalar field, one row of strings per point table.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Input {
    pub text: String,
    /// Point-table rows, each row one string per column.
    pub rows: Vec<Vec<String>>,
    /// The companion scalar of a point table (blank = not given).
    pub companion: String,
}

/// One parsed field of a would-be custom record, in the class's field order.
#[derive(Clone, Debug, PartialEq)]
pub struct Entry {
    pub key: String,
    pub value: Value,
}

/// The set of entries for one record.
pub type Values = Vec<Entry>;

pub fn get<'a>(vals: &'a Values, key: &str) -> Option<&'a Value> {
    vals.iter().find(|e| e.key == key).map(|e| &e.value)
}

pub fn number(vals: &Values, key: &str) -> Option<f64> {
    get(vals, key).and_then(|v| v.as_number())
}

pub fn text<'a>(vals: &'a Values, key: &str) -> Option<&'a str> {
    get(vals, key).and_then(|v| v.as_text())
}

pub fn list(vals: &Values, key: &str) -> Vec<String> {
    get(vals, key)
        .and_then(|v| v.as_list())
        .map(|x| x.to_vec())
        .unwrap_or_default()
}

pub fn points(vals: &Values, key: &str) -> Vec<Vec<f64>> {
    get(vals, key)
        .and_then(|v| v.as_points())
        .map(|x| x.to_vec())
        .unwrap_or_default()
}

// -------------------------------------------------------------------------------------- the parsing

/// `1.25` -> `"1.25"`, `1.0` -> `"1"`: the shortest honest form, for labels and summaries.
pub fn trim(v: f64) -> String {
    let s = format!("{v:.6}");
    let s = s.trim_end_matches('0').trim_end_matches('.');
    if s.is_empty() || s == "-" {
        "0".to_string()
    } else {
        s.to_string()
    }
}

fn range_text(min: Option<f64>, max: Option<f64>) -> String {
    match (min, max) {
        (Some(a), Some(b)) => format!("{}-{}", trim(a), trim(b)),
        (Some(a), None) => format!(">= {}", trim(a)),
        (None, Some(b)) => format!("<= {}", trim(b)),
        (None, None) => "any".to_string(),
    }
}

/// Parse one field's input. The returned error names the field and the problem; the *range* check is in
/// [`validate`], so a value outside the range parses and is then refused with the range quoted.
pub fn parse_input(spec: &Field, input: &Input) -> Result<Value, String> {
    let key = &spec.key;
    let t = input.text.trim();
    match spec.kind {
        Kind::Text => {
            if t.is_empty() {
                if spec.required {
                    return Err(format!("{key} is required"));
                }
                return Ok(Value::Text(String::new()));
            }
            Ok(Value::Text(t.to_string()))
        }
        Kind::Number => {
            if t.is_empty() {
                if spec.required {
                    return Err(format!("{key} is required"));
                }
                return Err(format!("{key} is blank"));
            }
            t.parse::<f64>()
                .map(Value::Number)
                .map_err(|_| format!("{key}: \"{t}\" is not a number"))
        }
        Kind::Range2 => {
            let parts: Vec<&str> = t.split(&[',', '/', ';'][..]).map(|s| s.trim()).collect();
            if parts.len() != 2 {
                return Err(format!("{key}: enter two numbers, lo,hi"));
            }
            let lo = parts[0]
                .parse::<f64>()
                .map_err(|_| format!("{key}: \"{}\" is not a number", parts[0]))?;
            let hi = parts[1]
                .parse::<f64>()
                .map_err(|_| format!("{key}: \"{}\" is not a number", parts[1]))?;
            Ok(Value::Range2(lo, hi))
        }
        Kind::TextList => {
            let items: Vec<String> = t
                .split(',')
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .collect();
            if items.is_empty() && spec.required {
                return Err(format!("{key} is required (a comma-separated list)"));
            }
            Ok(Value::TextList(items))
        }
        Kind::Points => {
            let mut rows: Vec<Vec<f64>> = Vec::new();
            for (i, row) in input.rows.iter().enumerate() {
                let cells: Vec<String> = row.iter().map(|c| c.trim().to_string()).collect();
                if cells.iter().all(|c| c.is_empty()) {
                    continue; // a blank row the user has not filled in yet is not a row
                }
                if cells.len() != spec.columns.len() {
                    return Err(format!(
                        "{key}: row {} has {} value(s), the table has {} column(s)",
                        i + 1,
                        cells.len(),
                        spec.columns.len()
                    ));
                }
                let mut nums = Vec::with_capacity(cells.len());
                for (c, cell) in cells.iter().enumerate() {
                    let v = cell.parse::<f64>().map_err(|_| {
                        format!(
                            "{key}: row {} column {} (\"{}\") is not a number",
                            i + 1,
                            spec.columns[c].key,
                            cell
                        )
                    })?;
                    nums.push(v);
                }
                rows.push(nums);
            }
            if rows.len() < 2 {
                return Err(format!(
                    "{key} needs at least 2 points (the engine interpolates the table); {} given",
                    rows.len()
                ));
            }
            Ok(Value::Points(rows))
        }
        Kind::Object => {
            let mut out = Vec::new();
            for sub in spec.sub.iter() {
                let cell = t
                    .split(',')
                    .nth(spec.sub.iter().position(|s| s.key == sub.key).unwrap_or(0))
                    .unwrap_or("")
                    .trim();
                if cell.is_empty() {
                    if sub.required {
                        return Err(format!("{key}.{} is required", sub.key));
                    }
                    continue;
                }
                let v = cell
                    .parse::<f64>()
                    .map_err(|_| format!("{key}.{}: \"{cell}\" is not a number", sub.key))?;
                out.push((sub.key.clone(), v));
            }
            if out.is_empty() {
                return Err(format!("{key} is required"));
            }
            Ok(Value::Object(out))
        }
    }
}

/// The rule that refuses a value: names the field, the value and **the range**.
pub fn validate(spec: &Field, value: &Value) -> Result<(), String> {
    let key = &spec.key;
    let out_of = |v: f64, unit: &str| -> Result<(), String> {
        let within =
            spec.min.map(|m| v >= m).unwrap_or(true) && spec.max.map(|m| v <= m).unwrap_or(true);
        if within {
            Ok(())
        } else {
            let unit = if unit.is_empty() {
                String::new()
            } else {
                format!(" {unit}")
            };
            Err(format!(
                "{key} {} is outside {}{} - the range the bundled catalog records for this field",
                trim(v),
                range_text(spec.min, spec.max),
                unit
            ))
        }
    };
    match value {
        Value::Number(v) => out_of(*v, &spec.unit)?,
        Value::Range2(a, b) => {
            if a > b {
                return Err(format!(
                    "{key} {}..{} is inverted (low must not exceed high)",
                    trim(*a),
                    trim(*b)
                ));
            }
            out_of(*a, &spec.unit)?;
            out_of(*b, &spec.unit)?;
        }
        Value::Points(rows) => {
            for (i, r) in rows.iter().enumerate() {
                if !(r[0].is_finite() && r.iter().all(|x| x.is_finite())) {
                    return Err(format!("{key}: row {} has a value that is not finite", i + 1));
                }
            }
            if spec.monotonic {
                let x: Vec<f64> = rows.iter().map(|r| r[0]).collect();
                for i in 1..x.len() {
                    if x[i] <= x[i - 1] {
                        return Err(format!(
                            "{key} must be monotonic in {}: row {} ({}) does not exceed row {} ({})",
                            spec.columns.first().map(|c| c.key.as_str()).unwrap_or("x"),
                            i + 1,
                            trim(x[i]),
                            i,
                            trim(x[i - 1])
                        ));
                    }
                }
            }
            if let Some(c) = &spec.companion {
                // The companion scalar's range is checked where the caller parses it
                // ([`parse_companion`]); its presence here is what tells the form to draw the input.
                debug_assert!(!c.key.is_empty());
            }
        }
        Value::Object(pairs) => {
            for (k, v) in pairs {
                let sub = spec.sub.iter().find(|s| &s.key == k);
                let (min, max) = sub.map(|s| (s.min, s.max)).unwrap_or((None, None));
                let within =
                    min.map(|m| *v >= m).unwrap_or(true) && max.map(|m| *v <= m).unwrap_or(true);
                if !within {
                    let unit = sub.map(|s| s.unit.as_str()).unwrap_or("");
                    return Err(format!(
                        "{key}.{k} {} is outside {}{} - the range the bundled catalog records",
                        trim(*v),
                        range_text(min, max),
                        if unit.is_empty() { String::new() } else { format!(" {unit}") }
                    ));
                }
            }
        }
        Value::TextList(items) => {
            if !spec.one_of.is_empty() {
                for it in items {
                    if !spec.one_of.iter().any(|x| x == it) {
                        return Err(format!(
                            "{key}: \"{it}\" is not one of the catalog's own values [{}]",
                            spec.one_of.join(", ")
                        ));
                    }
                }
            }
        }
        Value::Text(s) => {
            if !spec.one_of.is_empty() && !s.is_empty() && !spec.one_of.iter().any(|x| x == s) {
                return Err(format!(
                    "{key}: \"{s}\" is not one of the catalog's own values [{}]",
                    spec.one_of.join(", ")
                ));
            }
        }
    }
    Ok(())
}

/// Parse **and** validate one field: what the Save button runs for every field of the form.
pub fn parse_and_validate(spec: &Field, input: &Input) -> Result<Value, String> {
    let v = parse_input(spec, input)?;
    validate(spec, &v)?;
    Ok(v)
}

/// True when the user has left this control untouched. An *optional* field that is blank is not an error:
/// the record simply does not carry it (the engine's own record type holds it as `Option<...>`).
pub fn is_blank(input: &Input) -> bool {
    input.text.trim().is_empty() && input.rows.iter().all(|r| r.iter().all(|c| c.trim().is_empty())) && input.companion.trim().is_empty()
}

/// **Everything the Save button does for one field**, in one call: the field's own entry, plus its
/// companion scalar's entry under the companion's own key (`atDryAirLoadingKgM2S`), plus the refusal when
/// a value is out of the range the bundled catalog records.
///
/// Returns an empty vector for an optional field the user left blank - the record then omits it.
pub fn parse_field_entries(spec: &Field, input: &Input) -> Result<Vec<Entry>, String> {
    if !spec.required && is_blank(input) {
        return Ok(Vec::new());
    }
    let mut out = Vec::new();
    let value = parse_and_validate(spec, input)?;
    out.push(Entry {
        key: spec.key.clone(),
        value,
    });
    if let Some(c) = &spec.companion {
        let v = parse_companion(spec, input)?.ok_or_else(|| {
            format!("{} is required for {}", c.key, spec.key)
        })?;
        out.push(Entry {
            key: c.key.clone(),
            value: Value::Number(v),
        });
    }
    Ok(out)
}

/// The companion scalar of a point table, which the form asks for beside the rows.
pub fn parse_companion(spec: &Field, input: &Input) -> Result<Option<f64>, String> {
    let Some(c) = &spec.companion else {
        return Ok(None);
    };
    let t = input.companion.trim();
    if t.is_empty() {
        return Err(format!("{} is required for {}", c.key, spec.key));
    }
    let v = t
        .parse::<f64>()
        .map_err(|_| format!("{}: \"{t}\" is not a number", c.key))?;
    let within = c.min.map(|m| v >= m).unwrap_or(true) && c.max.map(|m| v <= m).unwrap_or(true);
    if !within {
        return Err(format!(
            "{} {} is outside {}{} - the range the bundled catalog records",
            c.key,
            trim(v),
            range_text(c.min, c.max),
            if c.unit.is_empty() {
                String::new()
            } else {
                format!(" {}", c.unit)
            }
        ));
    }
    Ok(Some(v))
}

/// A field's own range, in words, for the form's hint line.
pub fn range_hint(spec: &Field) -> String {
    match spec.kind {
        Kind::Number | Kind::Range2 => {
            let r = range_text(spec.min, spec.max);
            if r == "any" {
                String::new()
            } else if spec.unit.is_empty() || spec.unit == "-" {
                r
            } else {
                format!("{r} {}", spec.unit)
            }
        }
        Kind::Points => format!(
            "at least 2 rows{}",
            if spec.monotonic { ", x increasing" } else { "" }
        ),
        Kind::Object => "numbers, comma-separated, in this order".to_string(),
        Kind::TextList => "comma-separated".to_string(),
        Kind::Text => spec.one_of.join(" | "),
    }
}

// =============================================================================== the saved record

/// A record the user authored in this session: its class and the values the form produced.
///
/// This is what the rail holds, what the picker lists and what a drop writes into the machine - through
/// the *same* `PartRef` / `check_drop` / `apply_drop` path a catalog card takes, because the record is
/// built into the engine's own type below and then lives in the session catalog beside the fixture's.
/// A record the user authored. Where it lives changed in issue #74 (D26): it is part of the **project
/// file**, not of the page's session - see [`PERSISTENCE_PUBLIC`] and [`PERSISTENCE_INTERNAL`].
#[derive(Clone, Debug, PartialEq)]
pub struct CustomPart {
    /// `fan` / `drift` / `fill` / `nozzle` (the descriptor's class slugs).
    pub class: String,
    pub values: Values,
}

/// What happens to a custom record now that a project is a file (issue #74, D26). The app prints this in
/// the form's footer. The public host keeps its own rule: it can author, and it cannot save or export.
pub const PERSISTENCE_PUBLIC: &str =
    "Saved in the project file when you save one - the public host cannot save or export, so these records \
     live in this page until then.";
/// The internal host's version: the same file, and the connect issue that will push it later.
pub const PERSISTENCE_INTERNAL: &str = "Saved in the project file: `File > Save` on the native app, \
     `download project` here. A later server connect (ServerCommand::SaveRevision) pushes the same file - \
     nothing is sent anywhere today.";

impl CustomPart {
    pub fn new(class: impl Into<String>, values: Values) -> Self {
        Self {
            class: class.into(),
            values,
        }
    }

    /// The record's id, as the user typed it.
    pub fn id(&self) -> String {
        text(&self.values, "id").unwrap_or_default().to_string()
    }

    fn spec<'a>(&self, fields: &'a Fields) -> Result<&'a ClassSpec, String> {
        fields
            .class(&self.class)
            .ok_or_else(|| format!("no field list for class {}", self.class))
    }

    /// Build the engine's own fan record from the values (the record is used by `check_drop` and by
    /// `Engine::run` itself, so this is the boundary the whole feature rests on).
    pub fn to_fan(&self, fields: &Fields) -> Result<cockpit::engine::FanRecord, String> {
        let spec = self.spec(fields)?;
        let curve = &curve_field(spec, "curve")?;
        let pts = need_points(&self.values, "curve")?;
        let (xi, yi, ei) = (
            col(curve, "flowM3S")?,
            col(curve, "pressurePa")?,
            col(curve, "efficiency")?,
        );
        Ok(cockpit::engine::FanRecord {
            id: self.id(),
            name: String::new(),
            stack_area_m2: need_num(&self.values, "stackAreaM2")?,
            pressure_basis: text(&self.values, "pressureBasis").unwrap_or("total").to_string(),
            reference_density_kg_m3: need_num(&self.values, "referenceDensityKgM3")?,
            stack_recovery_factor: opt_num(&self.values, "stackRecoveryFactor"),
            allowed_speed_ratio: {
                let (lo, hi) = need_range2(&self.values, "allowedSpeedRatio")?;
                [lo, hi]
            },
            // The fixture's own field list (`fixtures-fields.json`) does not offer a rated speed
            // yet, so a custom fan record states none and the rpm read-out shows `-`; a form that
            // grows the field is read here without a second mapping.
            nominal_rpm: opt_num(&self.values, "nominalRpm"),
            drive_efficiency: need_num(&self.values, "driveEfficiency")?,
            motor_efficiency: need_num(&self.values, "motorEfficiency")?,
            curve: pts
                .iter()
                .map(|r| cockpit::engine::FanPoint {
                    flow_m3_s: r[xi],
                    pressure_pa: r[yi],
                    efficiency: r[ei],
                })
                .collect(),
        })
    }

    /// Build the engine's own drift-eliminator record.
    pub fn to_drift(&self, fields: &Fields) -> Result<cockpit::engine::DriftRecord, String> {
        let spec = self.spec(fields)?;
        let curve = &curve_field(spec, "curve")?;
        let pts = need_points(&self.values, "curve")?;
        let (vi, di, pi) = (
            col(curve, "faceVelocityMS")?,
            col(curve, "driftPpm")?,
            col(curve, "pressureDropPa")?,
        );
        Ok(cockpit::engine::DriftRecord {
            id: self.id(),
            name: String::new(),
            max_water_temperature_c: need_num(&self.values, "maxWaterTemperatureC")?,
            curve: pts
                .iter()
                .map(|r| cockpit::engine::DriftPoint {
                    face_velocity_m_s: r[vi],
                    drift_ppm: r[di],
                    pressure_drop_pa: r[pi],
                })
                .collect(),
        })
    }

    /// Build the fill record **and** its sampled characteristic - the table the engine interpolates.
    pub fn to_fill(&self, fields: &Fields) -> Result<cockpit::fixture_engine::FixtureFill, String> {
        let spec = self.spec(fields)?;
        let characteristic = &curve_field(spec, "characteristic")?;
        let pts = need_points(&self.values, "characteristic")?;
        let (wi, ki, pai) = (
            col(characteristic, "waterLoadingKgM2S")?,
            col(characteristic, "kavlPerM")?,
            col(characteristic, "paPerM")?,
        );
        let companion = characteristic
            .companion
            .as_ref()
            .ok_or("the fill characteristic has no companion scalar in the field list")?;
        let at_dry = opt_num(&self.values, &companion.key).ok_or_else(|| {
            format!(
                "{} is required for the fill characteristic",
                companion.key
            )
        })?;
        let obj = |key: &str| -> Result<Vec<(String, f64)>, String> {
            get(&self.values, key)
                .and_then(|v| v.as_object())
                .map(|o| o.to_vec())
                .ok_or_else(|| format!("{key} is missing"))
        };
        let sub = |o: &Vec<(String, f64)>, k: &str| -> Result<f64, String> {
            o.iter()
                .find(|(key, _)| key == k)
                .map(|(_, v)| *v)
                .ok_or_else(|| format!("{k} is missing"))
        };
        let thermal = obj("thermal")?;
        let pressure = obj("pressure")?;
        let limits = obj("limits")?;
        let record = cockpit::engine::FillRecord {
            id: self.id(),
            name: String::new(),
            geometry: String::new(),
            compatible_tower_types: list(&self.values, "compatibleTowerTypes"),
            allowed_water_quality_classes: list(&self.values, "allowedWaterQualityClasses"),
            thermal: cockpit::engine::FillThermal {
                coefficient_per_m: sub(&thermal, "coefficientPerM")?,
                reference_water_loading_kg_m2_s: sub(&thermal, "referenceWaterLoadingKgM2S")?,
                reference_dry_air_loading_kg_m2_s: sub(&thermal, "referenceDryAirLoadingKgM2S")?,
                water_exponent: sub(&thermal, "waterExponent")?,
                air_exponent: sub(&thermal, "airExponent")?,
            },
            pressure: cockpit::engine::FillPressure {
                coefficient_pa_per_m: sub(&pressure, "coefficientPaPerM")?,
                reference_water_loading_kg_m2_s: sub(&pressure, "referenceWaterLoadingKgM2S")?,
                reference_dry_air_loading_kg_m2_s: sub(&pressure, "referenceDryAirLoadingKgM2S")?,
                water_exponent: sub(&pressure, "waterExponent")?,
                air_exponent: sub(&pressure, "airExponent")?,
            },
            limits: cockpit::engine::FillLimits {
                min_water_loading_kg_m2_s: sub(&limits, "minWaterLoadingKgM2S")?,
                max_water_loading_kg_m2_s: sub(&limits, "maxWaterLoadingKgM2S")?,
                min_dry_air_loading_kg_m2_s: sub(&limits, "minDryAirLoadingKgM2S")?,
                max_dry_air_loading_kg_m2_s: sub(&limits, "maxDryAirLoadingKgM2S")?,
                max_water_temperature_c: sub(&limits, "maxWaterTemperatureC")?,
            },
        };
        Ok(cockpit::fixture_engine::FixtureFill {
            record,
            characteristic: cockpit::fixture_engine::Characteristic {
                at_dry_air_loading_kg_m2_s: at_dry,
                points: pts
                    .iter()
                    .map(|r| cockpit::fixture_engine::CharPoint {
                        water_loading_kg_m2_s: r[wi],
                        kavl_per_m: r[ki],
                        pa_per_m: r[pai],
                    })
                    .collect(),
            },
        })
    }

    /// Build the engine's own nozzle record.
    pub fn to_nozzle(&self, fields: &Fields) -> Result<cockpit::engine::NozzleRecord, String> {
        let _ = self.spec(fields)?;
        Ok(cockpit::engine::NozzleRecord {
            id: self.id(),
            name: text(&self.values, "name").unwrap_or("").to_string(),
            discharge_coefficient: need_num(&self.values, "dischargeCoefficient")?,
            orifice_diameter_m: need_num(&self.values, "orificeDiameterM")?,
            reference_water_density_kg_m3: opt_num(&self.values, "referenceWaterDensityKgM3"),
        })
    }

    /// The record, as the one line the app's flash strip shows.
    pub fn summary(&self) -> String {
        let keys: Vec<String> = self.values.iter().map(|e| e.key.clone()).collect();
        format!("{} · {} field(s): {}", self.class, keys.len(), keys.join(", "))
    }
}

/// The descriptor for a field that must be a point table.
fn curve_field<'a>(spec: &'a ClassSpec, key: &str) -> Result<&'a Field, String> {
    spec.fields
        .iter()
        .find(|f| f.key == key)
        .ok_or_else(|| format!("the field list has no {key}"))
}

/// The column index of a point table's column, by the catalog's own key.
fn col(field: &Field, key: &str) -> Result<usize, String> {
    field
        .columns
        .iter()
        .position(|c| c.key == key)
        .ok_or_else(|| format!("{} has no {} column", field.key, key))
}

fn need_num(vals: &Values, key: &str) -> Result<f64, String> {
    number(vals, key).ok_or_else(|| format!("{key} is missing"))
}

fn need_range2(vals: &Values, key: &str) -> Result<(f64, f64), String> {
    get(vals, key)
        .and_then(|v| v.as_range2())
        .ok_or_else(|| format!("{key} is missing"))
}

fn opt_num(vals: &Values, key: &str) -> Option<f64> {
    number(vals, key)
}

fn need_points(vals: &Values, key: &str) -> Result<Vec<Vec<f64>>, String> {
    let p = points(vals, key);
    if p.len() < 2 {
        return Err(format!("{key} needs at least 2 points"));
    }
    Ok(p)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fields_json() -> String {
        include_str!("../../assets/custom-fields.json").to_string()
    }

    fn spec(slug: &str, key: &str) -> Field {
        let f = Fields::from_json(&fields_json()).expect("descriptor parses");
        f.class(slug)
            .expect("class")
            .fields
            .iter()
            .find(|x| x.key == key)
            .expect("field")
            .clone()
    }

    #[test]
    fn descriptor_is_generated_for_four_classes() {
        let f = Fields::from_json(&fields_json()).expect("parses");
        assert_eq!(f.classes.len(), 4, "fan / drift / fill / nozzle");
        for c in f.classes.iter() {
            assert!(!c.fields.is_empty(), "{} has fields", c.class);
            // Every field carries a unit (an empty one reads as "-") and says where it came from.
            for x in c.fields.iter() {
                assert!(!x.unit.is_empty(), "{}.{} has no unit", c.class, x.key);
                assert!(!x.from.is_empty(), "{}.{} does not say where it comes from", c.class, x.key);
            }
        }
    }

    #[test]
    fn the_fan_field_list_is_the_fixture_field_list() {
        // The order and the names are fixtures-fields.json's, verbatim.
        let f = Fields::from_json(&fields_json()).unwrap();
        let keys: Vec<&str> = f
            .class("fan")
            .unwrap()
            .fields
            .iter()
            .map(|x| x.key.as_str())
            .collect();
        assert_eq!(
            keys,
            vec![
                "id",
                "stackAreaM2",
                "pressureBasis",
                "referenceDensityKgM3",
                "stackRecoveryFactor",
                "allowedSpeedRatio",
                "driveEfficiency",
                "motorEfficiency",
                "curve"
            ]
        );
    }

    #[test]
    fn a_number_out_of_range_is_refused_and_the_range_is_named() {
        let s = spec("fan", "stackAreaM2");
        let err = parse_and_validate(
            &s,
            &Input {
                text: "99".into(),
                ..Default::default()
            },
        )
        .expect_err("99 m2 is outside the catalog's span");
        assert!(err.contains("stackAreaM2"), "{err}");
        assert!(err.contains("outside"), "{err}");
        assert!(err.contains(&trim(s.min.unwrap())), "names the lower bound: {err}");
        assert!(err.contains("m2"), "names the unit: {err}");
        // and the value at the top of the range is accepted
        let ok = parse_and_validate(
            &s,
            &Input {
                text: trim(s.max.unwrap()),
                ..Default::default()
            },
        );
        assert!(ok.is_ok(), "{ok:?}");
    }

    #[test]
    fn a_blank_required_field_is_refused() {
        let s = spec("fan", "stackAreaM2");
        let err = parse_and_validate(&s, &Input::default()).expect_err("required");
        assert!(err.contains("required"), "{err}");
    }

    #[test]
    fn a_point_table_needs_two_rows_and_a_rising_x() {
        let s = spec("fan", "curve");
        assert!(parse_and_validate(&s, &Input::default()).is_err());
        let one = Input {
            rows: vec![vec!["10".into(), "200".into(), "0.6".into()]],
            ..Default::default()
        };
        let err = parse_and_validate(&s, &one).expect_err("one row is not a table");
        assert!(err.contains("2 points"), "{err}");
        let flat = Input {
            rows: vec![
                vec!["10".into(), "200".into(), "0.6".into()],
                vec!["10".into(), "180".into(), "0.7".into()],
            ],
            ..Default::default()
        };
        let err = parse_and_validate(&s, &flat).expect_err("x must rise");
        assert!(err.contains("monotonic"), "{err}");
        let rising = Input {
            rows: vec![
                vec!["10".into(), "200".into(), "0.6".into()],
                vec!["14".into(), "180".into(), "0.7".into()],
            ],
            ..Default::default()
        };
        assert!(parse_and_validate(&s, &rising).is_ok());
    }

    #[test]
    fn the_fill_characteristic_carries_its_companion() {
        let s = spec("fill", "characteristic");
        let rows = vec![
            vec!["0.5".into(), "0.9".into(), "30".into()],
            vec!["1.5".into(), "0.8".into(), "45".into()],
        ];
        // The Save button's own call: the table without its companion scalar is refused, and the refusal
        // names the missing field.
        let input = Input {
            rows: rows.clone(),
            ..Default::default()
        };
        let err = parse_field_entries(&s, &input).expect_err("the companion is required");
        assert!(err.contains("atDryAirLoadingKgM2S"), "{err}");
        // With the companion inside the range the catalog records, the field yields TWO entries: the table
        // and the companion under its own key.
        let c = s.companion.clone().unwrap();
        let input = Input {
            rows: rows.clone(),
            companion: trim(c.min.unwrap()),
            ..Default::default()
        };
        let entries = parse_field_entries(&s, &input).expect("parses");
        assert_eq!(entries.len(), 2, "{entries:?}");
        assert_eq!(entries[1].key, "atDryAirLoadingKgM2S");
        assert_eq!(entries[1].value.as_number(), Some(c.min.unwrap()));
        // Outside the range it is refused, and the range is named.
        let input = Input {
            rows,
            companion: "900".into(),
            ..Default::default()
        };
        let err = parse_field_entries(&s, &input).expect_err("companion out of range");
        assert!(err.contains("outside"), "{err}");
        assert!(err.contains("atDryAirLoadingKgM2S"), "{err}");
    }

    #[test]
    fn an_optional_field_left_blank_is_simply_absent() {
        // `fan.stackRecoveryFactor` and `nozzle.referenceWaterDensityKgM3` are the engine's own
        // `Option<...>` fields: blank is not an error, and the saved record does not carry them.
        for (class, key) in [("fan", "stackRecoveryFactor"), ("nozzle", "referenceWaterDensityKgM3")] {
            let s = spec(class, key);
            assert!(!s.required, "{class}.{key} is optional");
            let entries = parse_field_entries(&s, &Input::default()).expect("blank is fine");
            assert!(entries.is_empty(), "{entries:?}");
        }
        // A required field left blank is still refused.
        let s = spec("fan", "stackAreaM2");
        let err = parse_field_entries(&s, &Input::default()).expect_err("required");
        assert!(err.contains("required"), "{err}");
    }

    #[test]
    fn a_text_list_outside_the_catalog_vocabulary_is_refused() {
        let s = spec("fill", "compatibleTowerTypes");
        let err = parse_and_validate(
            &s,
            &Input {
                text: "counterflow, sideways".into(),
                ..Default::default()
            },
        )
        .expect_err("sideways is not a tower type in the catalog");
        assert!(err.contains("sideways"), "{err}");
        assert!(err.contains("counterflow"), "names the vocabulary: {err}");
    }

    #[test]
    fn an_object_field_validates_each_sub_number() {
        let s = spec("fill", "limits");
        let err = parse_and_validate(
            &s,
            &Input {
                // limits: min/max water loading, min/max dry-air loading, max water temperature. The last
                // one leaves the recorded span (55-90 C); the first four are inside theirs.
                text: "1.2, 5.0, 0.9, 3.3, 999".into(),
                ..Default::default()
            },
        )
        .expect_err("999 C is outside the catalog's span");
        assert!(err.contains("limits.maxWaterTemperatureC"), "{err}");
        assert!(err.contains("outside"), "{err}");
    }

    #[test]
    fn an_inverted_range_is_refused() {
        let s = spec("fan", "allowedSpeedRatio");
        // The catalog's own span for this field is 0.66-1.15, so an inverted pair inside it is a shape
        // error rather than a range error - which is the rule this test is about.
        let err = parse_and_validate(
            &s,
            &Input {
                text: "1.10,0.70".into(),
                ..Default::default()
            },
        )
        .expect_err("inverted");
        assert!(err.contains("inverted"), "{err}");
        let ok = parse_and_validate(
            &s,
            &Input {
                text: "0.70,1.10".into(),
                ..Default::default()
            },
        );
        assert!(ok.is_ok(), "{ok:?}");
    }

    // ---- round 4: the record a save builds ---------------------------------------------------------

    fn fields() -> Fields {
        Fields::from_json(&fields_json()).expect("descriptor")
    }

    /// The values a form leaves behind, built through the *same* call the Save button runs
    /// ([`parse_field_entries`]) - including the companion scalar's own entry.
    fn values_from(class: &str, inputs: &[(&str, Input)]) -> Values {
        let f = fields();
        let spec = f.class(class).expect("class");
        let mut out = Values::new();
        for field in spec.fields.iter() {
            let input = inputs
                .iter()
                .find(|(k, _)| *k == field.key)
                .map(|(_, i)| i.clone())
                .unwrap_or_else(Input::default);
            let entries = parse_field_entries(field, &input)
                .unwrap_or_else(|e| panic!("{}.{}: {e}", class, field.key));
            out.extend(entries);
        }
        out
    }

    #[test]
    fn a_saved_fan_becomes_a_real_engine_record() {
        let part = CustomPart::new(
            "fan",
            values_from(
                "fan",
                &[
                    ("id", Input { text: "CP-FAN-01".into(), ..Default::default() }),
                    ("stackAreaM2", Input { text: "19.635".into(), ..Default::default() }),
                    ("pressureBasis", Input { text: "total".into(), ..Default::default() }),
                    ("referenceDensityKgM3", Input { text: "1.2".into(), ..Default::default() }),
                    ("allowedSpeedRatio", Input { text: "0.70, 1.13".into(), ..Default::default() }),
                    ("driveEfficiency", Input { text: "0.96".into(), ..Default::default() }),
                    ("motorEfficiency", Input { text: "0.95".into(), ..Default::default() }),
                    (
                        "curve",
                        Input {
                            rows: vec![
                                vec!["55".into(), "520".into(), "0.63".into()],
                                vec!["145".into(), "380".into(), "0.83".into()],
                            ],
                            ..Default::default()
                        },
                    ),
                ],
            ),
        );
        let rec = part.to_fan(&fields()).expect("a record");
        assert_eq!(rec.id, "CP-FAN-01");
        assert!((rec.stack_area_m2 - 19.635).abs() < 1e-9);
        assert_eq!(rec.allowed_speed_ratio, [0.70, 1.13]);
        // The point table's columns are mapped by the catalog's own key order, not by position luck.
        assert_eq!(rec.curve.len(), 2);
        assert!((rec.curve[1].flow_m3_s - 145.0).abs() < 1e-9);
        assert!((rec.curve[1].efficiency - 0.83).abs() < 1e-9);
        // The optional field the user left blank stays absent rather than becoming a zero.
        assert_eq!(rec.stack_recovery_factor, None);
        assert_eq!(part.id(), "CP-FAN-01");
        assert!(part.class == "fan");
    }

    #[test]
    fn a_saved_fill_carries_the_characteristic_the_engine_interpolates() {
        let part = CustomPart::new(
            "fill",
            values_from(
                "fill",
                &[
                    ("id", Input { text: "CP-FILL-01".into(), ..Default::default() }),
                    ("compatibleTowerTypes", Input { text: "counterflow".into(), ..Default::default() }),
                    ("allowedWaterQualityClasses", Input { text: "clean, moderate".into(), ..Default::default() }),
                    ("thermal", Input { text: "0.94, 3, 2, -0.27, 0.39".into(), ..Default::default() }),
                    ("pressure", Input { text: "43, 3, 2, 0.1, 1.67".into(), ..Default::default() }),
                    ("limits", Input { text: "1.1, 6.2, 0.8, 3.5, 75".into(), ..Default::default() }),
                    (
                        "characteristic",
                        Input {
                            rows: vec![
                                vec!["1.0".into(), "1.934".into(), "74.5".into()],
                                vec!["3.125".into(), "1.313".into(), "91.5".into()],
                                vec!["5.0".into(), "1.119".into(), "99.6".into()],
                            ],
                            // The catalog records ONE dry-air loading (2.1783), so the companion's span is that single value.
                            companion: "2.1783".into(),
                            ..Default::default()
                        },
                    ),
                ],
            ),
        );
        let fill = part.to_fill(&fields()).expect("a record");
        assert_eq!(fill.record.id, "CP-FILL-01");
        assert_eq!(fill.record.allowed_water_quality_classes, vec!["clean", "moderate"]);
        assert!((fill.record.limits.max_water_temperature_c - 75.0).abs() < 1e-9);
        assert_eq!(fill.characteristic.points.len(), 3);
        assert!((fill.characteristic.points[1].kavl_per_m - 1.313).abs() < 1e-9);
        assert!((fill.characteristic.at_dry_air_loading_kg_m2_s - 2.1783).abs() < 1e-9);
    }

    #[test]
    fn a_saved_nozzle_and_drift_become_records_too() {
        let nozzle = CustomPart::new(
            "nozzle",
            values_from(
                "nozzle",
                &[
                    ("id", Input { text: "CP-NZ-01".into(), ..Default::default() }),
                    ("name", Input { text: "CP full cone".into(), ..Default::default() }),
                    ("dischargeCoefficient", Input { text: "0.72".into(), ..Default::default() }),
                    ("orificeDiameterM", Input { text: "0.02".into(), ..Default::default() }),
                ],
            ),
        );
        let nz = nozzle.to_nozzle(&fields()).expect("record");
        assert_eq!(nz.id, "CP-NZ-01");
        assert!((nz.orifice_diameter_m - 0.02).abs() < 1e-12);
        assert_eq!(nz.reference_water_density_kg_m3, None);

        let drift = CustomPart::new(
            "drift",
            values_from(
                "drift",
                &[
                    ("id", Input { text: "CP-DE-01".into(), ..Default::default() }),
                    ("maxWaterTemperatureC", Input { text: "60".into(), ..Default::default() }),
                    (
                        "curve",
                        Input {
                            rows: vec![
                                vec!["1".into(), "4".into(), "10".into()],
                                vec!["3.5".into(), "38".into(), "101".into()],
                            ],
                            ..Default::default()
                        },
                    ),
                ],
            ),
        );
        let d = drift.to_drift(&fields()).expect("record");
        assert_eq!(d.id, "CP-DE-01");
        assert_eq!(d.curve.len(), 2);
        assert!((d.curve[1].drift_ppm - 38.0).abs() < 1e-9);
        assert!((d.curve[1].pressure_drop_pa - 101.0).abs() < 1e-9);
    }

    /// The note says where a custom record lives now: in the project file (issue #74, D26). The public
    /// host's copy still says, in the same breath, that the public host cannot save or export.
    #[test]
    fn the_persistence_note_is_the_shipped_copy() {
        assert!(PERSISTENCE_PUBLIC.contains("project file"));
        assert!(PERSISTENCE_PUBLIC.contains("cannot save or export"));
        assert!(PERSISTENCE_INTERNAL.contains("ServerCommand::SaveRevision"));
        assert!(PERSISTENCE_INTERNAL.contains("nothing is sent anywhere today"));
    }
}
