//! Round 4, change 4: **the duty & site panel's data, and the evidence gate behind it.**
//!
//! Pure Rust, no Bevy: the panel's seeds, the recorded limits, the psychrometric reference and the
//! `out of fixture range` rule are all decided here and unit-tested natively against the shipped files.
//!
//! Two sources, both recorded:
//!
//! 1. `viz/assets/duty-fields.json`, generated by `tools/gen-duty.mjs` from `../fixtures/engine-run.json`
//!    (`provenance.duty`, `provenance.fixed`, `rate.inputs.requirements`, `anchor.air`, `anchor.waterFlow`
//!    and `defaultInput.duty`). Every entry carries the JSON path it came from, so nothing in the panel is
//!    a number the pass chose: it is the engine's own recorded duty, limit or psychrometric state.
//! 2. `viz/assets/fixture.json`, the record the engine actually runs from, for the **evidence gate**: the
//!    domain of the sweeps the engine's own duty check accepted. Inside that domain the `FixtureEngine`
//!    interpolates what it recorded; outside it, the pass may not print a number at all - the read-out says
//!    [`OUT_OF_FIXTURE_RANGE`] instead. A test asserts the two sources agree (see the tests at the bottom).

use serde::Deserialize;

use crate::mapping;

/// The words a read-out shows instead of a number the fixture cannot evidence.
pub const OUT_OF_FIXTURE_RANGE: &str = "out of recorded range";

// ------------------------------------------------------------------------------------- the generated spec

/// One duty or water-quality field: the engine's own name, the panel's label, and the recorded value.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Seed {
    /// The engine's own field name (`Duty.water_flow_m3_hr` -> `waterFlowM3Hr`).
    pub key: String,
    /// The panel's plain-language label ("water flow").
    pub plain: String,
    pub unit: String,
    pub value: f64,
    /// The JSON path in `fixtures/engine-run.json` this came from.
    pub from: String,
    /// The panel's unit-conversion mode for this row, when the field has two spellings (`m3Hr` <-> `kgS`).
    #[serde(default)]
    pub mode: String,
    #[serde(default)]
    pub note: String,
}

/// One recorded limit (`provenance.fixed` / `rate.inputs.requirements`). `value: None` = the fixture
/// carries no value for this row, which the panel prints as "not recorded" rather than inventing one.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Limit {
    pub key: String,
    pub plain: String,
    pub unit: String,
    pub value: Option<f64>,
    pub from: String,
    #[serde(default)]
    pub note: String,
}

/// The recorded inlet state (`anchor.air.inlet`) - the fixture's own psychrometrics.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Inlet {
    pub dry_bulb_c: f64,
    pub wet_bulb_c: f64,
    pub relative_humidity: f64,
    pub humidity_ratio: f64,
    pub pressure_pa: f64,
    pub saturation_humidity_ratio: f64,
}

/// The psychrometric reference the relative-humidity row is derived from: the recorded inlet state, the
/// fixture's own saturation table, and the two water-flow conventions.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Psychro {
    pub inlet: Inlet,
    /// `anchor.air.saturation`: `[temperature C, saturation humidity ratio kg/kg]`, as recorded.
    pub saturation: Vec<[f64; 2]>,
    /// `anchor.waterFlow.waterDensityKgM3` - the density the *engine* converted with.
    pub water_density_kg_m3: f64,
    /// `anchor.waterFlow.m3Hr` and `anchor.waterFlow.kgS` - the engine's own converted pair.
    pub recorded_water_flow_m3_hr: f64,
    pub recorded_water_mass_flow_kg_s: f64,
}

impl Psychro {
    /// The recorded inlet humidity ratio: the scalar the derived relative humidity holds.
    pub fn inlet_humidity_ratio(&self) -> f64 {
        self.inlet.humidity_ratio
    }

    /// Saturation humidity ratio at a temperature, linearly interpolated in the fixture's own table.
    /// `None` outside the table's span (the pass does not extrapolate a psychrometric curve).
    pub fn saturation_ratio_at(&self, t_c: f64) -> Option<f64> {
        let pts = &self.saturation;
        if pts.len() < 2 {
            return None;
        }
        let (lo, hi) = (pts[0][0], pts[pts.len() - 1][0]);
        if t_c < lo - 1e-9 || t_c > hi + 1e-9 {
            return None;
        }
        for w in pts.windows(2) {
            let (a, b) = (w[0], w[1]);
            if t_c >= a[0] && t_c <= b[0] {
                if (b[0] - a[0]).abs() < 1e-12 {
                    return Some(a[1]);
                }
                return Some(a[1] + (b[1] - a[1]) * (t_c - a[0]) / (b[0] - a[0]));
            }
        }
        Some(pts[pts.len() - 1][1])
    }

    /// **Derived relative humidity** for an entered dry bulb: the recorded inlet humidity ratio over the
    /// fixture's own saturation humidity ratio at that dry bulb.
    ///
    /// This is a *stated definition of a display value*, not the engine's psychrometrics: at the recorded
    /// inlet itself it returns 0.6193 against the engine's 0.6313, and the panel prints both numbers side by
    /// side so the difference is visible rather than hidden. `None` when the dry bulb is outside the
    /// fixture's recorded saturation table, where no value can be read.
    pub fn relative_humidity_at(&self, dry_bulb_c: f64) -> Option<f64> {
        let w_sat = self.saturation_ratio_at(dry_bulb_c)?;
        if w_sat <= 0.0 {
            return None;
        }
        Some((self.inlet.humidity_ratio / w_sat).clamp(0.0, 1.0))
    }
}

/// The generated duty/site descriptor.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DutySpec {
    pub generated_by: String,
    pub source: String,
    pub note: String,
    /// The editable duty rows, in panel order.
    pub duty: Vec<Seed>,
    /// The editable water-quality rows.
    pub water_quality: Vec<Seed>,
    /// The recorded water-quality class (`provenance.fixed.waterQualityClass`) - a string, so it is not a
    /// numeric seed.
    #[serde(default)]
    pub water_quality_class: String,
    /// The engine's own water-quality vocabulary (`catalog.waterQualityFactors` keys).
    #[serde(default)]
    pub water_quality_classes: Vec<String>,
    /// Display-only rows: recorded, not used by the engine yet (and, where the fixture records no value,
    /// printed as `not recorded`).
    #[serde(default)]
    pub display_only: Vec<Limit>,
    /// The recorded limits (`provenance.fixed` / `rate.inputs.requirements`).
    pub limits: Vec<Limit>,
    pub psychro: Psychro,
    /// The recorded evidence domains, as the generator read them off the fixture's own sweeps.
    pub evidence: Evidence,
}

impl DutySpec {
    pub fn from_json(text: &str) -> Result<Self, String> {
        serde_json::from_str(text).map_err(|e| format!("duty-fields.json: {e}"))
    }

    pub fn seed(&self, key: &str) -> Option<&Seed> {
        self.duty
            .iter()
            .chain(self.water_quality.iter())
            .find(|s| s.key == key)
    }

    pub fn limit(&self, key: &str) -> Option<&Limit> {
        self.limits.iter().find(|l| l.key == key)
    }

    /// The recorded duty value for a key, in the fixture's own units (`None` when absent).
    pub fn value_of(&self, key: &str) -> Option<f64> {
        self.seed(key).map(|s| s.value)
    }
}

// --------------------------------------------------------------------------------------- the evidence

/// The domain of the sweeps the engine's own duty check accepted - the range the pass may interpolate in.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Evidence {
    /// Water flow: the feasible points of `anchor.sweeps.waterMassFlowKgS`, in m3/hr at 1000 kg/m3.
    pub water_flow_m3_hr: [f64; 2],
    /// Entering wet bulb: the feasible points of `anchor.sweeps.wetBulbC`, in C.
    pub wet_bulb_c: [f64; 2],
    /// The recorded (pre-conversion) mass flows the row above was converted from.
    pub water_mass_flow_kg_s: [f64; 2],
    /// What the domain is, in words, for the panel's own note.
    pub note: String,
}

/// What the current duty does to the evidence gate.
#[derive(Clone, Debug, PartialEq)]
pub struct Verdict {
    pub flow_in_range: bool,
    pub wet_bulb_in_range: bool,
    /// One line per input that left its recorded domain, naming the domain.
    pub out_of_range: Vec<String>,
}

impl Verdict {
    /// True when every duty input the fixture records a sweep for is inside it.
    pub fn in_range(&self) -> bool {
        self.flow_in_range && self.wet_bulb_in_range
    }
    /// The amber line the read-out shows for one of its own rows.
    pub fn label(&self) -> &'static str {
        OUT_OF_FIXTURE_RANGE
    }
}

impl Evidence {
    /// Read the domains out of the bundled fixture text (the record the engine runs from).
    pub fn from_fixture_json(text: &str) -> Option<Evidence> {
        let v: serde_json::Value = serde_json::from_str(text).ok()?;
        let anchor = v.get("anchor")?;
        let fill_id = anchor.get("anchorFillId")?.as_str()?.to_string();
        let sweeps = anchor.get("sweeps")?;
        let flow_kg_s = feasible_span(sweeps.get("waterMassFlowKgS")?, &fill_id)?;
        let wb = feasible_span(sweeps.get("wetBulbC")?, &fill_id)?;
        Some(Evidence {
            water_flow_m3_hr: [
                mapping::m3_hr_from_kg_s(flow_kg_s[0]),
                mapping::m3_hr_from_kg_s(flow_kg_s[1]),
            ],
            wet_bulb_c: wb,
            water_mass_flow_kg_s: flow_kg_s,
            note: format!(
                "the feasible points of the fixture's own sweeps ({fill_id}): the duty the engine's check accepted"
            ),
        })
    }

    /// The verdict for a duty, in the fixture's own recorded units.
    pub fn verdict(&self, water_flow_m3_hr: f64, wet_bulb_c: f64) -> Verdict {
        let [flo, fhi] = self.water_flow_m3_hr;
        let [wlo, whi] = self.wet_bulb_c;
        let mut out = Vec::new();
        let flow_in_range = water_flow_m3_hr >= flo - 1e-6 && water_flow_m3_hr <= fhi + 1e-6;
        if !flow_in_range {
            out.push(format!(
                "water flow {:.0} m3/hr is outside the recorded {:.0}-{:.0} m3/hr sweep ({:.0}-{:.0} kg/s)",
                water_flow_m3_hr,
                flo,
                fhi,
                self.water_mass_flow_kg_s[0],
                self.water_mass_flow_kg_s[1]
            ));
        }
        let wet_bulb_in_range = wet_bulb_c >= wlo - 1e-6 && wet_bulb_c <= whi + 1e-6;
        if !wet_bulb_in_range {
            out.push(format!(
                "entering wet bulb {:.1} C is outside the recorded {:.1}-{:.1} C sweep",
                wet_bulb_c, wlo, whi
            ));
        }
        Verdict {
            flow_in_range,
            wet_bulb_in_range,
            out_of_range: out,
        }
    }
}

/// The span of the sweep points the engine itself accepted (`infeasible` false, cold water present).
fn feasible_span(sweep: &serde_json::Value, fill_id: &str) -> Option<[f64; 2]> {
    let pts = sweep
        .get("series")?
        .get(fill_id)?
        .as_array()?
        .iter()
        .filter(|p| !p.get("infeasible").and_then(|i| i.as_bool()).unwrap_or(false))
        .filter(|p| p.get("coldWaterC").and_then(|c| c.as_f64()).is_some())
        .filter_map(|p| p.get("x").and_then(|x| x.as_f64()))
        .collect::<Vec<f64>>();
    if pts.is_empty() {
        return None;
    }
    let lo = pts.iter().cloned().fold(f64::INFINITY, f64::min);
    let hi = pts.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    Some([lo, hi])
}

#[cfg(test)]
mod tests {
    use super::*;

    const DUTY: &str = include_str!("../../assets/duty-fields.json");
    const FIXTURE: &str = include_str!("../../assets/fixture.json");

    fn spec() -> DutySpec {
        DutySpec::from_json(DUTY).expect("the generated duty descriptor parses")
    }

    #[test]
    fn the_panel_is_seeded_from_the_recorded_duty_and_fixed_block() {
        let s = spec();
        // provenance.duty / provenance.fixed, verbatim.
        assert!((s.value_of("waterMassFlowKgS").unwrap() - 200.0).abs() < 1e-9);
        assert!((s.value_of("hotWaterC").unwrap() - 42.0).abs() < 1e-9);
        assert!((s.value_of("targetColdWaterC").unwrap() - 32.0).abs() < 1e-9);
        assert!((s.value_of("wetBulbC").unwrap() - 27.0).abs() < 1e-9);
        assert!((s.value_of("dryBulbC").unwrap() - 33.0).abs() < 1e-9);
        assert!((s.value_of("pressurePa").unwrap() - 101_325.0).abs() < 1e-9);
        assert!((s.value_of("salinityGKg").unwrap() - 0.0).abs() < 1e-9);
        assert!((s.value_of("cyclesOfConcentration").unwrap() - 4.0).abs() < 1e-9);
        assert_eq!(s.water_quality_class, "moderate");
        assert!(s.water_quality_classes.iter().any(|c| c == "moderate"));
        assert_eq!(s.water_quality_classes.len(), 3, "clean / moderate / dirty");
        // The display-only rows are present, carry no value and say they are unused.
        assert_eq!(s.display_only.len(), 3);
        assert!(s.display_only.iter().all(|l| l.value.is_none()));
        assert!(s
            .display_only
            .iter()
            .all(|l| l.note.contains("not used by the engine yet")));
        // Every row says where it came from.
        for row in s.duty.iter().chain(s.water_quality.iter()) {
            assert!(!row.from.is_empty(), "{} has no source", row.key);
            assert!(!row.unit.is_empty(), "{} has no unit", row.key);
            assert!(!row.plain.is_empty(), "{} has no label", row.key);
        }
    }

    #[test]
    fn the_limits_are_the_recorded_ones_and_the_nozzle_drop_names_its_source() {
        let s = spec();
        let want = [
            ("maxDriftPpm", 30.0),
            ("maxElectricalInputKW", 75.0),
            ("maxFootprintM2", 130.0),
            ("minimumThermalMarginC", 0.0),
            ("nozzlePressureDropPa", 65_000.0),
        ];
        for (k, v) in want {
            let l = s.limit(k).unwrap_or_else(|| panic!("{k} missing"));
            assert!((l.value.expect("recorded") - v).abs() < 1e-9, "{k}");
            assert!(l.from.contains("engine-run.json"), "{k}: {}", l.from);
        }
        assert!(
            s.limit("nozzlePressureDropPa").unwrap().from.contains("rate.inputs.requirements"),
            "the nozzle drop is only recorded in rate.inputs.requirements"
        );
    }

    #[test]
    fn the_psychrometric_reference_reproduces_the_recorded_inlet_and_reads_its_own_table() {
        let s = spec();
        let p = &s.psychro;
        assert!((p.inlet.dry_bulb_c - 33.0).abs() < 1e-9);
        assert!((p.inlet.wet_bulb_c - 27.0).abs() < 1e-9);
        // The fixture's own table at the recorded dry bulb is the recorded saturation ratio ...
        let w_sat = p.saturation_ratio_at(33.0).expect("inside the table");
        assert!((w_sat - p.inlet.saturation_humidity_ratio).abs() < 1e-6);
        // ... and the derived relative humidity at the recorded dry bulb is the recorded humidity ratio
        // over it - printed beside the engine's own 0.6313, not instead of it.
        let rh = p.relative_humidity_at(33.0).expect("derived");
        assert!((rh - 0.6193).abs() < 2e-3, "{rh}");
        assert!((rh - p.inlet.relative_humidity).abs() > 0.005, "the two differ, and both are shown");
        // Outside the table there is no value to read - never an extrapolation.
        assert!(p.relative_humidity_at(200.0).is_none());
        assert!(p.saturation_ratio_at(-40.0).is_none());
    }

    #[test]
    fn the_evidence_domains_are_the_ones_the_engine_accepted() {
        let s = spec();
        let from_fixture = Evidence::from_fixture_json(FIXTURE).expect("the fixture carries the sweeps");
        assert!(
            (s.evidence.water_flow_m3_hr[0] - from_fixture.water_flow_m3_hr[0]).abs() < 1e-6,
            "{:?} vs {:?}",
            s.evidence.water_flow_m3_hr,
            from_fixture.water_flow_m3_hr
        );
        assert!(s.evidence.water_flow_m3_hr[1] <= 800.0, "the sweep stops at 210 kg/s");
        assert_eq!(s.evidence.wet_bulb_c, [21.0, 27.0]);
        // 200 kg/s (the recorded duty) is inside the recorded sweep; the recorded wet bulb is inside too.
        let v = s.evidence.verdict(720.0, 27.0);
        assert!(v.in_range(), "{:?}", v.out_of_range);
        assert_eq!(v.label(), OUT_OF_FIXTURE_RANGE);
    }

    #[test]
    fn a_duty_outside_the_recorded_sweep_is_named_not_guessed() {
        let s = spec();
        let v = s.evidence.verdict(1_200.0, 31.5);
        assert!(!v.in_range());
        assert_eq!(v.out_of_range.len(), 2, "{:?}", v.out_of_range);
        let text = v.out_of_range.join(" | ");
        assert!(text.contains("1200 m3/hr"), "{text}");
        assert!(text.contains("504-756"), "names the recorded domain: {text}");
        assert!(text.contains("31.5"), "{text}");
        assert!(text.contains("21.0-27.0"), "{text}");
        // One input out of range is enough, and it names only that one.
        let one = s.evidence.verdict(720.0, 30.0);
        assert!(!one.in_range() && one.flow_in_range && one.out_of_range.len() == 1);
    }
}
