/**
 * Workflow lint (issue #92): this repository's Actions minutes are billed, so a pull request and
 * a push to `staging` start the `quick` tier and nothing else. It also guards the mirror image in
 * the public snapshot: the generated public CI must stay untiered (public runners are free).
 *
 * It reads every workflow under `WORKFLOW_LINT_ROOT/.github/workflows` (default: this repository)
 * and enforces, fail-closed:
 *
 *   * the workflow triggers match its shape — the private one: `pull_request`, a push to
 *     `main`/`staging`, `workflow_dispatch`; the generated public CI: `pull_request` and a push
 *     to `main`, nothing else;
 *   * a `quick` job exists exactly when the workflow is the private one, and in the private
 *     workflow every job is classified — quick or heavy (the list below) — with the quick job
 *     itself ungated (a gate on it would leave a PR running nothing);
 *   * every heavy job carries the private gate, spelled one way:
 *     `github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'` — and no job
 *     in the generated public CI carries it (the public suite must not skip a job on a PR);
 *   * no workflow that can trigger on `pull_request` or on a push to `staging` carries a job that
 *     reaches a macOS or Windows runner, or a heavy job, without that gate;
 *   * the private quick tier carries its four legs — the format gate, the static check, the fast
 *     unit suite, and the snapshot leak gate (the builder and the checker together) — while the
 *     generated public CI keeps the full chain and the plane build;
 *   * the job a pull request may start — the private `quick` tier, or the generated public CI's
 *     `validate` job — carries **no escape hatch** (fix contract 2): no `|| true` / `|| :` /
 *     `set +e` in any step's `run:`, no `continue-on-error` (step level or job level), and no
 *     echo-only step. A leg that cannot fail the job is not a gate, so each of those shapes is
 *     refused, named with its step and line;
 *   * the release workflow the builder emits (issue #102) keeps the properties a consumer pins
 *     by: a `v*` tag push and a dispatch dry run, public (`ubuntu`) runners only, no repository
 *     secret, the plane built through its gated build script, the plane's three parts asserted
 *     before packing, and the archive + `.sha256` + manifest published — with the recognition
 *     sentence below, so this lint reads it as generated rather than as a private workflow.
 *
 * The generated public CI is recognised by the provenance sentence its builder writes into it
 * (`GENERATED` below, from `scripts/public-snapshot.mjs`); a file that loses that sentence is
 * checked against the private rules instead — loudly, never silently.
 *
 * The parse is deliberately small: it understands this repository's workflow shape (two-space
 * block indentation, inline lists) and throws on a shape it does not recognise, so a workflow
 * that grows something this lint cannot read fails loudly rather than passing unread. Comments
 * are stripped before step bodies are matched, so a commented-out command does not count.
 *
 * `WORKFLOW_LINT_ROOT` exists for the RED probe: copy `.github/workflows`, mutate the copy,
 * point the lint at it.
 */
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const workflowDir = join(process.env.WORKFLOW_LINT_ROOT ?? root, '.github', 'workflows');

/** The gate every heavy job must carry — one spelling, no synonyms, no quotes. */
const GATE = "github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'";

/**
 * The provenance sentence the builder writes into the generated public CI
 * (`scripts/public-snapshot.mjs`, `PUBLIC_VALIDATE_WORKFLOW`). A public repository's standard
 * runners are free, so that workflow is deliberately untiered; this lint keys on the sentence to
 * check it against the public shape instead of the private one. A file that loses the sentence
 * falls back to the private rules — loudly, which is the failure mode we want.
 */
const GENERATED = "generated by the private repository's snapshot builder";

/** The private jobs that may not run on a pull request or a push to `staging` (issue #92). */
const HEAVY = [
  'validate',
  'rust',
  'wasm',
  'cockpit',
  'cockpit-native',
  'cockpit-native-platforms',
  'deployment-serving',
  'deployment'
];

/** The one job a pull request and a push to `staging` may start. */
const QUICK = ['quick'];

/** The workflow the classification rules apply to. */
const PR_WORKFLOW = 'validate.yml';

/** The quick tier's four legs (issue #92), matched against the comment-stripped job body. */
const QUICK_LEGS = [
  'cargo fmt --check',
  'npm run static',
  'npm test',
  'scripts/public-snapshot.mjs',
  'scripts/public-snapshot-check.mjs'
];

const MAC_WIN = /macos|windows/i;

/**
 * The escape hatches the job a pull request may start must never carry (fix contract 2): a leg
 * that cannot fail the job is not a gate. Each entry names the shape and is matched against the
 * comment-stripped `run:` text of one step; `continue-on-error` and echo-only steps are
 * structural and checked separately below.
 */
const ESCAPES = [
  { shape: 'a `|| true` mask', re: /\|\|\s*['"]?true['"]?\b/ },
  { shape: 'a `|| :` mask', re: /\|\|\s*['"]?:['"]?(?=\s|$|;|#)/ },
  { shape: '`set +e`', re: /\bset\s+['"]?\+e['"]?(?=\s|$|;|#)/ }
];

const indentOf = (line) => line.length - line.trimStart().length;
const isBlankOrComment = (line) => line.trim() === '' || line.trimStart().startsWith('#');
const stripComments = (text) => text.split('\n').filter((line) => !line.trimStart().startsWith('#')).join('\n');

/**
 * Reads one step property. A `run:` block is the deeper-indented lines below it, kept verbatim
 * (the escape-hatch scan matches their text); an inline `run:` is the rest of the line.
 */
function readStepProperty(step, key, raw, lines, i) {
  const value = raw.trim();
  if (key === 'name') step.name = value;
  if (key === 'continue-on-error') step.continueOnError = { line: i + 1, value };
  if (key !== 'run') return;
  step.runLine = i + 1;
  if (!/^[|>][-+]?$/.test(value)) {
    step.run = value;
    return;
  }
  const block = [];
  for (let j = i + 1; j < lines.length; j += 1) {
    if (lines[j].trim() === '') {
      block.push(lines[j]);
      continue;
    }
    if (indentOf(lines[j]) <= 8) break;
    block.push(lines[j]);
  }
  step.run = block.join('\n').trim();
}

/**
 * The two blocks this lint reads: `on:` (the triggers) and `jobs:` (one entry per job, with
 * `runs-on:`, an optional `if:`, any `os:` matrix entries, and its steps — each with its line,
 * `run:` text and `continue-on-error`). Unknown shapes throw. The file is read from `workflowDir`
 * unless `dir` names another directory (the emitted-release checks below pass the builder's own
 * output).
 */
function parseWorkflow(file, dir = workflowDir) {
  const text = readFileSync(join(dir, file), 'utf8');
  const lines = text.split('\n');
  const at = (re) => lines.findIndex((line) => re.test(line));

  const onAt = at(/^on:\s*$/);
  assert.notEqual(onAt, -1, `${file}: no top-level \`on:\` block`);
  const triggers = { pull_request: false, workflow_dispatch: false, pushBranches: [] };
  for (let i = onAt + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (isBlankOrComment(line)) continue;
    if (indentOf(line) === 0) break;
    if (indentOf(line) !== 2) continue;
    const key = line.trim().replace(/:.*$/, '');
    if (key === 'pull_request') triggers.pull_request = true;
    if (key === 'workflow_dispatch') triggers.workflow_dispatch = true;
    if (key === 'push') {
      for (let j = i + 1; j < lines.length && indentOf(lines[j]) > 2; j += 1) {
        const branchLine = lines[j].trim();
        if (!branchLine.startsWith('branches:')) continue;
        const inline = branchLine.match(/^branches:\s*\[(.*)\]\s*$/);
        assert.ok(inline, `${file}:${j + 1}: push.branches is not an inline list this lint can read`);
        triggers.pushBranches = inline[1].split(',').map((name) => name.trim()).filter(Boolean);
      }
    }
  }

  const jobsAt = at(/^jobs:\s*$/);
  assert.notEqual(jobsAt, -1, `${file}: no top-level \`jobs:\` block`);
  const jobs = new Map();
  let current = null;
  let body = [];
  const commit = () => jobs.set(current.name, { ...current, body: body.join('\n') });
  for (let i = jobsAt + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (isBlankOrComment(line)) {
      if (current) body.push(line);
      continue;
    }
    if (indentOf(line) === 0) break;
    if (indentOf(line) === 2) {
      const key = line.match(/^  ([A-Za-z0-9_-]+):\s*$/);
      assert.ok(key, `${file}:${i + 1}: unrecognised line at job level: ${line}`);
      if (current) commit();
      current = { name: key[1], line: i + 1, runsOn: null, ifExpr: null, continueOnError: null, matrixOs: [], steps: [] };
      body = [];
      continue;
    }
    if (!current) continue;
    body.push(line);
    const property = indentOf(line) === 4 ? line.match(/^    ([A-Za-z_-]+):\s*(.*)$/) : null;
    if (property?.[1] === 'runs-on') current.runsOn = property[2].trim();
    if (property?.[1] === 'if') current.ifExpr = property[2].trim();
    if (property?.[1] === 'continue-on-error') current.continueOnError = { line: i + 1, value: property[2].trim() };
    const os = line.match(/^\s+os:\s*\[(.*)\]\s*$/);
    if (os) current.matrixOs.push(...os[1].split(',').map((name) => name.trim()).filter(Boolean));
    const dash = line.match(/^ {6}- (.*)$/);
    if (dash) {
      const step = { line: i + 1, name: null, run: null, runLine: null, continueOnError: null };
      current.steps.push(step);
      const inline = dash[1].match(/^([A-Za-z_-]+):\s*(.*)$/);
      if (inline) readStepProperty(step, inline[1], inline[2], lines, i);
      continue;
    }
    const step = current.steps[current.steps.length - 1];
    if (step && indentOf(line) === 8) {
      const own = line.match(/^ {8}([A-Za-z_-]+):\s*(.*)$/);
      if (own) readStepProperty(step, own[1], own[2], lines, i);
    }
  }
  if (current) commit();

  assert.ok(jobs.size > 0, `${file}: \`jobs:\` carries no jobs`);
  for (const [name, job] of jobs) assert.ok(job.runsOn, `${file}: job \`${name}\` has no \`runs-on:\``);
  return { triggers, jobs, generated: text.includes(GENERATED) };
}

const reads = () => parseWorkflow(PR_WORKFLOW);
const reachesMacOrWindows = (job) => MAC_WIN.test(job.runsOn) || job.matrixOs.some((os) => MAC_WIN.test(os));

test('the workflow triggers match its shape', () => {
  const { triggers, generated } = reads();
  assert.equal(triggers.pull_request, true, 'pull_request is gone: pull requests would start nothing');
  if (generated) {
    // The generated public CI: public runners are free, so its whole suite runs on a PR and on a
    // push to its own `main`. It serves no lane branch, so it must not grow a dispatch trigger.
    assert.deepEqual(
      triggers.pushBranches.sort(),
      ['main'],
      `the generated public CI pushes to [${triggers.pushBranches.join(', ')}], expected main`
    );
    assert.equal(triggers.workflow_dispatch, false, 'the generated public CI grew a dispatch trigger');
    return;
  }
  assert.equal(
    triggers.workflow_dispatch,
    true,
    'workflow_dispatch is gone: a lane branch could no longer be proven on the hosted runner'
  );
  assert.deepEqual(
    [...triggers.pushBranches].sort(),
    ['main', 'staging'],
    `the private workflow pushes to [${triggers.pushBranches.join(', ')}], expected main and staging`
  );

  /* ------------------------------------------------------------------ *
   * The generated public release workflow (issue #102). The checks run
   * inside this test rather than as a new top-level one on purpose: the
   * suite's total test count is drift-pinned to VALIDATION_RESULTS.md,
   * and that figure must not move while two lanes share the tree.
   * ------------------------------------------------------------------ */
  {
    const scratch = mkdtempSync(join(tmpdir(), 'drafthouse-release-workflow-'));
    // The builder writes only into a directory that does not exist yet; `mkdtempSync` made one,
    // so the tree is one level below it.
    const out = join(scratch, 'snapshot');
    try {
      const env = { ...process.env };
      // The builder is a plain script, not a test-runner child; make sure it cannot be taken
      // for one when this suite itself runs under `node --test`.
      delete env.NODE_TEST_CONTEXT;
      const built = spawnSync(
        process.execPath,
        [join(root, 'scripts', 'public-snapshot.mjs'), '--out', out, '--ref', 'HEAD'],
        { cwd: root, encoding: 'utf8', env }
      );
      assert.equal(
        built.status,
        0,
        `the snapshot builder exited ${built.status} while emitting the release workflow:\n${built.stderr.slice(-2000)}`
      );

      const emitted = join(out, '.github', 'workflows', 'release.yml');
      assert.ok(existsSync(emitted), 'the builder emitted no .github/workflows/release.yml');
      const text = readFileSync(emitted, 'utf8');

      // The recognition sentence: with it, this lint reads the file as the generated public CI
      // (untiered, no private gate); without it, as a private workflow — loudly, which is the
      // failure mode we want.
      assert.ok(
        text.includes(GENERATED),
        `the emitted release workflow lost the provenance sentence ${JSON.stringify(GENERATED)}`
      );

      // The trigger: a `v*` tag push plus a dispatch dry run — and the file must parse with this
      // lint's own parser (it throws on a shape it cannot read).
      const parsed = parseWorkflow('release.yml', join(out, '.github', 'workflows'));
      assert.equal(parsed.generated, true, 'the emitted release workflow is not recognised as generated');
      assert.ok(text.includes("tags: ['v*']"), "the emitted release workflow has no `v*` tag trigger");
      assert.equal(parsed.triggers.workflow_dispatch, true, 'the emitted release workflow lost its dry-run dispatch');
      assert.equal(parsed.triggers.pull_request, false, 'the emitted release workflow gained a pull_request trigger');
      assert.deepEqual([...parsed.jobs.keys()].sort(), ['release', 'verify'], 'the emitted release workflow lost a job');

      // Public runners only, and no repository secret: the default GITHUB_TOKEN is the one
      // credential a public repository may use.
      assert.ok(!/macos|windows/i.test(text), 'the emitted release workflow reaches a macOS or Windows runner');
      const runsOn = [...text.matchAll(/^    runs-on: (.+)$/gm)].map((match) => match[1].trim());
      assert.ok(runsOn.length > 0, 'the emitted release workflow has no runs-on entries');
      assert.ok(
        runsOn.every((value) => value === 'ubuntu-latest'),
        `the emitted release workflow runs on [${runsOn.join(', ')}], expected ubuntu-latest only`
      );
      assert.ok(!text.includes('secrets.'), 'the emitted release workflow references a repository secret');
      assert.ok(text.includes('github.token'), 'the emitted release workflow does not use the default token');

      // The gzip size gate, the plane's three parts, and the release it publishes.
      assert.ok(
        text.includes('cockpit/tools/build-web.sh release'),
        'the emitted release workflow no longer builds the plane through its gated build script'
      );
      for (const part of [
        'cockpit/index.html',
        'cockpit/pkg/drafthouse_cockpit.js',
        'cockpit/pkg/drafthouse_cockpit_bg.wasm',
        'cockpit/assets/'
      ]) {
        assert.ok(text.includes(part), `the emitted release workflow does not assert the plane's ${part}`);
      }
      for (const published of ['gh release create', '--verify-tag', 'dist/cockpit/*', 'github.sha']) {
        assert.ok(text.includes(published), `the emitted release workflow does not publish ${published}`);
      }
      assert.ok(
        text.includes('gh release download') && text.includes('--verify dist/downloaded'),
        'the emitted release workflow lost the fresh-download verification of its own release'
      );
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  }
});

test('the quick tier exists exactly when this is the private workflow', () => {
  const { jobs, generated } = reads();
  assert.equal(
    jobs.has('quick'),
    !generated,
    generated
      ? 'the generated public CI grew a `quick` job: its suite is not tiered'
      : 'the private workflow lost its `quick` tier (issue #92): a PR would start the heavy jobs'
  );
  if (generated) return;
  assert.deepEqual(
    [...jobs.keys()].sort(),
    [...QUICK, ...HEAVY].sort(),
    'a job was added or renamed in the private workflow: classify it in this lint as quick or heavy '
      + '(issue #92 — anything unclassified may be burning billed minutes on pull requests)'
  );
  for (const name of QUICK) {
    assert.equal(jobs.get(name).ifExpr, null, `the quick job \`${name}\` is gated; a PR would start nothing`);
  }
});

test('the private gate is on every heavy job — and nowhere in the generated public CI', () => {
  const { jobs, generated } = reads();
  if (generated) {
    for (const [name, job] of jobs) {
      assert.notEqual(
        job.ifExpr,
        GATE,
        `the generated public CI's \`${name}\` carries the private dispatch/main gate: the public `
          + 'suite is not tiered and must not skip a job on a pull request'
      );
    }
    return;
  }
  for (const name of HEAVY) {
    assert.equal(
      jobs.get(name).ifExpr,
      GATE,
      `heavy job \`${name}\` does not carry the exact gate:\n  if: ${GATE}`
    );
  }
});

test('no private workflow runs a macOS/Windows or heavy job on a pull_request or a staging push', () => {
  const files = workflowFiles();
  assert.ok(files.length > 0, `${workflowDir} carries no workflow files`);
  for (const file of files) {
    const { triggers, jobs, generated } = parseWorkflow(file);
    if (generated) continue; // the public CI: free runners, deliberately untiered
    const reachable = triggers.pull_request || triggers.pushBranches.includes('staging');
    if (!reachable) continue;
    for (const [name, job] of jobs) {
      const mustBeGated = HEAVY.includes(name) || reachesMacOrWindows(job);
      if (!mustBeGated) continue;
      assert.equal(
        job.ifExpr,
        GATE,
        `${file}: \`${name}\` can run on a pull request or a push to staging (runner `
          + `\`${job.runsOn}\`${job.matrixOs.length ? `, matrix ${job.matrixOs.join(', ')}` : ''}) — `
          + `it needs:\n  if: ${GATE}`
      );
    }
  }
});

/**
 * Refuses every escape hatch (fix contract 2) in the job a pull request may start. Each failure
 * names the file, the line, the step and the shape, so a masked leg cannot slip through.
 */
function assertNoEscapeHatch(file, job) {
  const stepName = (step) => `step ${JSON.stringify(step.name ?? '(unnamed)')}`;
  assert.equal(
    job.continueOnError,
    null,
    `${file}:${job.continueOnError?.line ?? job.line}: the job \`${job.name}\` carries `
      + `\`continue-on-error: ${job.continueOnError?.value ?? ''}\` — a job a pull request may start must be able to fail`
  );
  for (const step of job.steps) {
    if (step.continueOnError) {
      assert.fail(
        `${file}:${step.continueOnError.line}: ${stepName(step)} carries `
          + `\`continue-on-error: ${step.continueOnError.value}\` — a step a pull request may start must be able to fail the job`
      );
    }
    const run = stripComments(step.run ?? '');
    for (const { shape, re } of ESCAPES) {
      const hit = run.match(re);
      assert.ok(
        !hit,
        `${file}:${step.runLine ?? step.line}: ${stepName(step)} uses ${shape} (\`${hit?.[0] ?? ''}\`) — `
          + 'a leg that swallows its own failure is not a gate'
      );
    }
    const commands = run.split('\n').map((line) => line.trim()).filter(Boolean);
    assert.ok(
      commands.length === 0 || !commands.every((command) => command.startsWith('echo')),
      `${file}:${step.runLine ?? step.line}: ${stepName(step)} is an echo-only step (\`${commands[0] ?? ''}\`) — `
        + 'a step that cannot fail is not a gate'
    );
  }
}

test('the job a pull request may start carries its legs and no escape hatch', () => {
  const { jobs, generated } = reads();
  if (generated) {
    const full = stripComments(jobs.get('validate').body);
    for (const leg of ['npm run validate', 'build-web.sh release']) {
      assert.ok(full.includes(leg), `the generated public CI no longer runs \`${leg}\``);
    }
    assertNoEscapeHatch(PR_WORKFLOW, jobs.get('validate'));
    return;
  }
  const quick = jobs.get('quick');
  const body = stripComments(quick.body);
  for (const leg of QUICK_LEGS) {
    assert.ok(body.includes(leg), `the quick tier no longer runs \`${leg}\` (issue #92)`);
  }
  assertNoEscapeHatch(PR_WORKFLOW, quick);
});

/** The workflow files, sorted, so the reachability test is deterministic. */
const workflowFiles = () => readdirSync(workflowDir)
  .filter((name) => name.endsWith('.yml') || name.endsWith('.yaml'))
  .sort();
