//! Round 4, item 4: **the duty & site panel.** Round 5, item 1: it is three **collapsible** sections.
//!
//! This is the one place in the pass where fixture values become editable. Every row is seeded from the
//! engine's own recorded run (`viz/assets/duty-fields.json`, generated by `tools/gen-duty.mjs` from
//! `../fixtures/engine-run.json`), every edit re-runs `Engine::run` (the UI pass runs the engine on the
//! draft every frame), and the panel shows:
//!
//! - the engine's own field names and units, with the plain-language label beside them;
//! - the two derived duty quantities (range, approach) live, read-only;
//! - the dry-bulb / relative-humidity pair with **one editable and the other derived**, labelled;
//! - the water-quality section, including the display-only TDS / chloride / pH note row;
//! - the recorded limits, each with the block it came from;
//! - the engine's own validation and the panel's own pre-check, both naming the physical limit.
//!
//! And one rule the whole frame obeys: where the fixture records no evidence for an edited duty (outside the
//! domain of the sweeps the engine itself accepted), no number is printed - the read-out and the panel both
//! say [`OUT_OF_FIXTURE_RANGE`] in amber. The rule and its arithmetic live in `drafthouse_cockpit_seams::duty`.
//!
//! ## Round 5: no row may clip
//!
//! The owner's report was that the right column clips, and at 1440x900 it did: the widest row of this form
//! measured 377 px inside a 304 px content box, so the scroll content grew past the column and the whole
//! card - values, units and all - ran off the right edge of the screen. Two changes answer it:
//!
//! 1. the column is 400 px at 1280 px viewports and above (see `crate::ui::RIGHT_W_WIDE`), and
//! 2. **every row measures itself** (`measure_ui`) and wraps a two-value row onto a second line when the
//!    column cannot hold both halves - never clipping, and never dropping a unit.
//!
//! Each such row is also reported to the clip probe, so `tools/clip-check.mjs` can assert it per evidence
//! frame instead of trusting the layout.

use bevy::prelude::*;
use bevy_egui::egui;
use egui::RichText;

use cockpit::engine::Duty;
use drafthouse_cockpit_seams::duty::{DutySpec, Verdict, OUT_OF_FIXTURE_RANGE};
use drafthouse_cockpit_seams::mapping as m;

use crate::app::{Draft, HitMap};
use crate::clip::{ClipProbe, LayoutInfo, CARET_CLOSED, CARET_OPEN};
use crate::state::{Flash, Run, Visual};
use crate::theme as t;

/// The generated duty/site descriptor, or the reason it could not be read.
#[derive(Resource, Clone, Default)]
pub struct DutyRes {
    pub spec: Option<DutySpec>,
    pub error: Option<String>,
}

/// The verdict for a duty under the loaded spec (`None` when no spec is loaded).
pub fn verdict(res: &DutyRes, duty: &Duty) -> Option<Verdict> {
    res.spec
        .as_ref()
        .map(|s| s.evidence.verdict(duty.water_flow_m3_hr, duty.wet_bulb_c))
}

/// The amber line a gated read-out row shows instead of a number.
pub fn out_of_range_text() -> RichText {
    RichText::new(OUT_OF_FIXTURE_RANGE)
        .size(12.5)
        .color(t::AMBER)
}

/// Does this duty leave the recorded evidence? `true` also when no spec is loaded (nothing can be
/// evidenced without the descriptor).
pub fn out_of_range(res: &DutyRes, duty: &Duty) -> bool {
    verdict(res, duty).map(|v| !v.in_range()).unwrap_or(true)
}

/// Round 5: measure a text unit with the same font the frame draws it with, so the wrap decision matches
/// the painter instead of guessing from a character count.
fn measure_ui(ui: &egui::Ui, text: &str, size: f32, family: egui::FontFamily) -> f32 {
    ui.painter()
        .layout_no_wrap(
            text.to_owned(),
            egui::FontId::new(size, family),
            egui::Color32::WHITE,
        )
        .size()
        .x
}

/// Round 5, item 1(b): one collapsible section header - a caret, the section's title, and (when the section
/// is collapsed) the one-line summary of what is inside it, on its own line below the title. Both lines are
/// the click target, so a phone can hit it, and the header reports itself to the clip probe with the
/// *measured* width of the summary - one row could not hold title and summary: with the title in place the
/// summary had ~150 px and its first unit was cut (`… max drift 30.0 p…`), which is exactly the "a value
/// without its unit" the owner's item 1 rules out.
const SECTION_SUMMARY_INDENT: f32 = 16.0;

#[allow(clippy::too_many_arguments)]
fn section_header(
    ui: &mut egui::Ui,
    hits: &mut HitMap,
    clip: &mut ClipProbe,
    info: &mut LayoutInfo,
    key: &str,
    probe: &str,
    title: &str,
    summary: &str,
    open: bool,
) -> bool {
    let head = ui
        .horizontal(|ui| {
            ui.label(
                RichText::new(if open { CARET_OPEN } else { CARET_CLOSED })
                    .size(10.5)
                    .color(t::PRIMARY)
                    .family(t::family_mono_med()),
            );
            ui.label(t::eyebrow(title));
        })
        .response
        .rect;
    // An open header is title-only. A collapsed one gets a second line for its summary, indented under the
    // title, with the full width of the section to fit in.
    let (row, need) = if open {
        (
            head,
            measure_ui(ui, title, 9.5, egui::FontFamily::Proportional) + SECTION_SUMMARY_INDENT,
        )
    } else {
        let need =
            measure_ui(ui, summary, 9.5, egui::FontFamily::Proportional) + SECTION_SUMMARY_INDENT;
        let line = ui
            .horizontal(|ui| {
                ui.add_space(SECTION_SUMMARY_INDENT);
                ui.add(
                    egui::Label::new(RichText::new(summary).size(9.5).color(t::INK_2)).truncate(),
                );
            })
            .response
            .rect;
        (head.union(line), need)
    };
    // The whole column width is the target, not just the words: a section header is a control.
    let mut target = row;
    target.max.x = target.max.x.max(ui.max_rect().right() - 2.0);
    let avail = target.width();
    clip.push(
        format!("panel.{probe}.header"),
        if open {
            title.to_string()
        } else {
            format!("{title}  {summary}")
        },
        target,
        avail,
        need,
        if open { 1 } else { 2 },
    );
    // The header reports its own rect and state in one marker, so a click can be checked against the layout
    // that produced it rather than against a rect read a frame earlier.
    if !info.section_rects.is_empty() {
        info.section_rects.push(';');
    }
    info.section_rects.push_str(&format!(
        "{probe}:{:.0},{:.0},{:.0},{:.0},{}",
        target.min.x,
        target.min.y,
        target.width(),
        target.height(),
        if open { 1 } else { 0 }
    ));
    hits.0.push((
        key.to_string(),
        [target.min.x, target.min.y, target.width(), target.height()],
    ));
    ui.interact(target, egui::Id::new(key), egui::Sense::click())
        .on_hover_cursor(egui::CursorIcon::PointingHand)
        .on_hover_text(if open {
            "collapse this section"
        } else {
            "expand this section"
        })
        .clicked()
}

/// The panel. `draft` is the live engine input: every edit writes `duty.*` and the next frame's
/// `Engine::run` sees it.
#[allow(clippy::too_many_arguments)]
pub fn panel(
    ui: &mut egui::Ui,
    draft: Option<&mut Draft>,
    res: &DutyRes,
    run: &Run,
    vis: &mut Visual,
    hits: &mut HitMap,
    clip: &mut ClipProbe,
    info: &mut LayoutInfo,
    phone: bool,
) {
    let Some(draft) = draft else {
        return;
    };
    let Some(spec) = res.spec.as_ref() else {
        t::card_flat().show(ui, |ui| {
            ui.label(t::body(
                "the duty & site descriptor did not load, so nothing can be edited here.",
            ));
            if let Some(e) = &res.error {
                ui.label(RichText::new(e).size(10.0).color(t::DANGER));
            }
        });
        return;
    };

    let duty = &mut draft.0.duty;
    let v = spec
        .evidence
        .verdict(duty.water_flow_m3_hr, duty.wet_bulb_c);
    let mut reset = false;

    // ---- the three collapsed-header summaries (round 5, item 1(b)), each one line of values + units.
    let duty_summary = format!(
        "{} m³/h · {}/{} °C · wet bulb {} °C",
        t::num::flow(duty.water_flow_m3_hr),
        t::num::temp(duty.hot_water_c),
        t::num::temp(duty.target_cold_water_c),
        t::num::temp(duty.wet_bulb_c)
    );
    let water_summary = format!(
        "{} · salinity {} g/kg · cycles {}",
        duty.water_quality_class,
        t::fmt(duty.salinity_g_kg),
        t::fmt(duty.cycles_of_concentration)
    );
    let limit_of = |key: &str| -> String {
        spec.limits
            .iter()
            .find(|l| l.key == key)
            .and_then(|l| l.value)
            .map(t::fmt)
            .unwrap_or_else(|| "—".into())
    };
    let limits_summary = format!(
        "{} recorded · max drift {} ppm · max electrical input {} kW",
        spec.limits.len(),
        limit_of("maxDriftPpm"),
        limit_of("maxElectricalInputKW")
    );
    info.duty_summary = duty_summary.clone();
    info.water_summary = water_summary.clone();
    info.limits_summary = limits_summary.clone();
    info.duty_open = vis.duty_open;
    info.water_open = vis.water_open;
    info.limits_open = vis.limits_open;

    t::card_flat().show(ui, |ui| {
        // ---- the panel's own status row: the evidence chip and the reset, panel-wide rather than inside a
        // section, so they stay put whatever the sections do.
        let status = ui
            .horizontal_wrapped(|ui| {
                ui.label(t::eyebrow("duty & site"));
                if v.in_range() {
                    chip(ui, "inside the recorded sweep", t::VALID);
                } else {
                    chip(ui, OUT_OF_FIXTURE_RANGE, t::AMBER);
                }
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    if hit(
                        hits,
                        "ctl:duty-reset",
                        ui.add_sized(egui::vec2(120.0, 22.0), egui::Button::new("reset duty")),
                    )
                    .on_hover_text("back to the recorded duty and the recorded water quality")
                    .clicked()
                    {
                        reset = true;
                    }
                });
            })
            .response
            .rect;
        {
            let sweep = if v.in_range() {
                "inside the recorded sweep"
            } else {
                OUT_OF_FIXTURE_RANGE
            };
            let need = measure_ui(ui, "duty & site", 9.5, egui::FontFamily::Proportional)
                + measure_ui(ui, sweep, 9.5, t::family_semi())
                + 18.0
                + 120.0
                + 16.0;
            // The row wraps (the reset button drops to its own line) rather than clipping.
            let lines = if status.height() > 26.0 { 2 } else { 1 };
            clip.push(
                "panel.status",
                format!("duty & site · {sweep} · reset duty"),
                status,
                status.width(),
                need,
                lines,
            );
        }

        // ================================================================= DUTY & SITE
        if section_header(
            ui,
            hits,
            clip,
            info,
            "ctl:duty-toggle",
            "duty",
            "duty & site — editable",
            &duty_summary,
            vis.duty_open,
        ) {
            vis.duty_open = !vis.duty_open;
        }
        if vis.duty_open {
            // The body is a ~14-row form: it scrolls inside its own section (round 4's cap, now per section)
            // so the water-quality and limits headers - and the read-out below the panel - stay on screen.
            egui::ScrollArea::vertical()
                .id_salt("duty-panel")
                .auto_shrink([false, true])
                .max_height(170.0)
                .show(ui, |ui| {

                    // water flow: the brief's m3/hr at 1000 kg/m3, with the engine's own pair beside it.
                    let mut flow = duty.water_flow_m3_hr;
                    if edit_row(
                        ui,
                        clip,
                        "duty.water-flow",
                        "water flow",
                        "waterFlowM3Hr",
                        "m³/h",
                        &mut flow,
                        hits,
                        "ctl:duty-flow",
                        5.0,
                    ) {
                        duty.water_flow_m3_hr = flow;
                    }
                    let kg_s = m::kg_s_from_m3_hr(duty.water_flow_m3_hr);
                    // Issue #91: the engine's own pair is in the notes drawer; the form keeps the conversion.
                    ui.label(
                        RichText::new(format!("= {} kg/s", t::fmt(kg_s)))
                            .size(10.0)
                            .color(t::MUTED)
                            .family(t::family_mono_med()),
                    );
                    ui.add_space(2.0);
                    derived_strip(ui, duty, hits, clip);
                    ui.add_space(2.0);
                    let (hot, target) = edit_pair(
                        ui,
                        hits,
                        clip,
                        "duty.hot-target",
                        [
                            ("hot water", "ctl:duty-hot", duty.hot_water_c, "hotWaterC", 1.0, 1),
                            (
                                "target cold",
                                "ctl:duty-target",
                                duty.target_cold_water_c,
                                "targetColdWaterC",
                                1.0,
                                1,
                            ),
                        ],
                    );
                    duty.hot_water_c = hot;
                    duty.target_cold_water_c = target;

                    // the dry bulb / relative humidity pair (one editable, one derived)
                    let (wb, db) = edit_pair(
                        ui,
                        hits,
                        clip,
                        "duty.wet-dry",
                        [
                            ("wet bulb", "ctl:duty-wetbulb", duty.wet_bulb_c, "wetBulbC", 1.0, 1),
                            ("dry bulb", "ctl:duty-drybulb", duty.dry_bulb_c, "dryBulbC", 1.0, 1),
                        ],
                    );
                    duty.wet_bulb_c = wb;
                    duty.dry_bulb_c = db;
                    match spec.psychro.relative_humidity_at(duty.dry_bulb_c) {
                        Some(rh) => {
                            ro_row(
                                ui,
                                clip,
                                "duty.humidity",
                                "relative humidity (derived)",
                                &format!("{:.1} %", rh * 100.0),
                                "-",
                                false,
                            );
                            ui.label(
                                RichText::new(format!(
                                    "from the recorded inlet humidity ratio at {} °C · recorded inlet RH {} %",
                                    t::num::temp(duty.dry_bulb_c),
                                    t::num::pct(spec.psychro.inlet.relative_humidity * 100.0)
                                ))
                                .size(9.0)
                                .color(t::MUTED),
                            );
                        }
                        None => ro_row(
                            ui,
                            clip,
                            "duty.humidity",
                            "relative humidity (derived)",
                            "outside the recorded table",
                            "-",
                            false,
                        ),
                    }

                    // the site: pressure or altitude (same rule)
                    let mut p = duty.pressure_pa;
                    if edit_row(
                        ui,
                        clip,
                        "duty.pressure",
                        "barometric pressure",
                        "pressurePa",
                        "Pa",
                        &mut p,
                        hits,
                        "ctl:duty-pressure",
                        25.0,
                    ) {
                        duty.pressure_pa = p;
                    }
                    let alt = m::altitude_m_from_pressure_pa(duty.pressure_pa);
                    ro_row(
                        ui,
                        clip,
                        "duty.altitude",
                        "site altitude (derived)",
                        &format!("{alt:.1}"),
                        "m",
                        false,
                    );
                    ui.label(
                        RichText::new("pressure is the input; the altitude is its ISA equivalent, shown for reference")
                            .size(9.0)
                            .color(t::MUTED),
                    );
                });
        }

        // ================================================================= WATER QUALITY
        ui.add_space(2.0);
        if section_header(
            ui,
            hits,
            clip,
            info,
            "ctl:water-toggle",
            "water",
            "water quality",
            &water_summary,
            vis.water_open,
        ) {
            vis.water_open = !vis.water_open;
        }
        if vis.water_open {
            // `horizontal_wrapped`, not `horizontal`: the trailing qualifier ("waterQualityClass · the
            // engine's own enum", 9 px) makes this row 418 px wide in a 376 px column, and an unwrapped row
            // that wide grows the layout for every card below it (round 5's clip probe caught it: the read-out
            // and the fill stack were drawn 18 px wider, 30 px of them past the window's right edge).
            ui.horizontal_wrapped(|ui| {
                ui.label(RichText::new("water quality class").size(11.5).color(t::MUTED));
                let mut cls = duty.water_quality_class.clone();
                let before = cls.clone();
                egui::ComboBox::from_id_salt("duty.quality")
                    .selected_text(cls.clone())
                    .width(110.0)
                    .show_ui(ui, |ui| {
                        for c in spec.water_quality_classes.iter() {
                            ui.selectable_value(&mut cls, c.clone(), c);
                        }
                    });
                if cls != before {
                    duty.water_quality_class = cls;
                    vis.flash = Some(Flash {
                        ok: true,
                        text: format!(
                            "water quality class {} (the fill drop rules read it)",
                            duty.water_quality_class
                        ),
                    });
                }
                ui.label(
                    RichText::new("sets the fill's fouling allowance")
                        .size(9.0)
                        .color(t::MUTED),
                );
            });
            let mut sal = duty.salinity_g_kg;
            if edit_row(
                ui,
                clip,
                "water.salinity",
                "salinity",
                "salinityGKg",
                "g/kg",
                &mut sal,
                hits,
                "ctl:duty-salinity",
                0.5,
            ) {
                duty.salinity_g_kg = sal;
            }
            let mut cyc = duty.cycles_of_concentration;
            if edit_row(
                ui,
                clip,
                "water.cycles",
                "cycles of concentration",
                "cyclesOfConcentration",
                "-",
                &mut cyc,
                hits,
                "ctl:duty-cycles",
                0.25,
            ) {
                duty.cycles_of_concentration = cyc;
            }
            ui.label(
                RichText::new("make-up reads the cycles (blowdown = evaporation ÷ (cycles − 1)); salinity is recorded, not used in the calculation")
                    .size(9.0)
                    .color(t::MUTED),
            );
            // display-only rows: recorded, not used by the engine yet - and no value to invent.
            ui.horizontal_wrapped(|ui| {
                ui.label(RichText::new("display-only").size(9.5).color(t::MUTED));
                for l in spec.display_only.iter() {
                    chip(
                        ui,
                        &format!(
                            "{} {}",
                            l.plain,
                            l.value.map(t::fmt).unwrap_or_else(|| "—".into())
                        ),
                        t::MUTED,
                    );
                }
            });
            ui.label(
                RichText::new("TDS / chloride / pH: recorded, not used in the calculation yet")
                    .size(9.0)
                    .color(t::MUTED),
            );
        }

        // ================================================================= LIMITS
        ui.add_space(2.0);
        if section_header(
            ui,
            hits,
            clip,
            info,
            "ctl:limits-toggle",
            "limits",
            "limits — recorded requirements",
            &limits_summary,
            vis.limits_open,
        ) {
            vis.limits_open = !vis.limits_open;
        }
        if vis.limits_open {
            // Two cells to a row while the column can hold them, one when it cannot (round 4 used a fixed
            // 168 px cell: two of them plus the gap is 344 px, which is wider than a 344 px column's own
            // content box - the second cell's unit was the first thing to go off the edge).
            let avail = ui.available_width();
            let cell_w = 168.0;
            // Two-up only while every cell's own content fits its half: the widest recorded limit decides, not
            // the column width (round 5: the probe measures each cell's natural width against the width it
            // was given, and a cell that cannot hold its value *and* its unit falls back to one column).
            let widest = spec
                .limits
                .iter()
                .map(|l| {
                    let value = l.value.map(t::fmt).unwrap_or_else(|| "not recorded".into());
                    measure_ui(ui, &l.plain, 10.0, egui::FontFamily::Proportional)
                        + measure_ui(ui, &value, 10.5, t::family_mono_med())
                        + measure_ui(ui, &l.unit, 9.0, t::family_mono_med())
                        + 16.0
                })
                .fold(0.0f32, f32::max);
            let cols = if avail >= cell_w * 2.0 + 8.0 && widest <= cell_w - 4.0 {
                2
            } else {
                1
            };
            let w = if cols == 2 { cell_w } else { avail };
            for (n, chunk) in spec.limits.chunks(cols).enumerate() {
                ui.horizontal(|ui| {
                    for l in chunk {
                        let value = l
                            .value
                            .map(t::fmt)
                            .unwrap_or_else(|| "not recorded".into());
                        let need = measure_ui(ui, &l.plain, 10.0, egui::FontFamily::Proportional)
                            + measure_ui(ui, &value, 10.5, t::family_mono_med())
                            + measure_ui(ui, &l.unit, 9.0, t::family_mono_med())
                            + 16.0;
                        let resp = ui.allocate_ui_with_layout(
                            egui::vec2(w, 20.0),
                            egui::Layout::left_to_right(egui::Align::Center),
                            |ui| {
                                ui.label(RichText::new(&l.plain).size(10.0).color(t::MUTED));
                                ui.with_layout(
                                    egui::Layout::right_to_left(egui::Align::Center),
                                    |ui| {
                                        if l.unit != "-" {
                                            ui.label(
                                                RichText::new(&l.unit)
                                                    .size(9.0)
                                                    .color(t::MUTED)
                                                    .family(t::family_mono_med()),
                                            );
                                        }
                                        ui.label(
                                            RichText::new(&value)
                                                .size(10.5)
                                                .color(t::INK)
                                                .family(t::family_mono_med()),
                                        );
                                    },
                                );
                            },
                        );
                        clip.push(
                            format!("limits.row{n}.{}", l.key),
                            format!(
                                "{} {} {}",
                                l.plain,
                                value,
                                if l.unit == "-" { "" } else { &l.unit }
                            ),
                            resp.response.rect,
                            w,
                            need,
                            1,
                        );
                    }
                });
            }
            ui.label(
                RichText::new("every limit as recorded for this design, with its own name")
                    .size(9.0)
                    .color(t::MUTED),
            );
        }


        // ================================================================= VALIDATION + EVIDENCE GATE
        // These are state, not inputs: they stay visible whatever the sections are doing, because they are
        // the answer the panel exists to give.
        let mut any = false;
        if let Some(o) = run.output.as_ref() {
            if !o.validation.is_empty() {
                any = true;
                ui.add_space(4.0);
                ui.label(t::eyebrow("outside rated range"));
                for lim in o.validation.iter().take(4) {
                    ui.label(
                        RichText::new(format!("• {}", lim.message))
                            .size(10.0)
                            .color(t::DANGER),
                    );
                }
            }
        }
        let pre = precheck(duty);
        if !pre.is_empty() {
            any = true;
            ui.add_space(4.0);
            ui.label(t::eyebrow("duty pre-check"));
            for p in pre.iter() {
                ui.label(
                    RichText::new(format!("• {p}"))
                        .size(10.0)
                        .color(t::DANGER),
                );
            }
            ui.label(
                RichText::new("the calculation itself only refuses a target cold water at or below the wet bulb; both checks are shown")
                    .size(9.0)
                    .color(t::MUTED),
            );
        }
        let _ = any;

        // ---- the evidence gate
        ui.add_space(4.0);
        ui.horizontal_wrapped(|ui| {
            if v.in_range() {
                chip(ui, "in recorded range", t::VALID);
            } else {
                chip(ui, OUT_OF_FIXTURE_RANGE, t::AMBER);
            }
            // Issue #91: the evidence sentence is in the notes drawer; the ranges stay as numbers.
            ui.label(
                RichText::new(format!(
                    "{}–{} m³/h · wet bulb {}–{} °C",
                    t::num::flow(spec.evidence.water_flow_m3_hr[0]),
                    t::num::flow(spec.evidence.water_flow_m3_hr[1]),
                    t::num::temp(spec.evidence.wet_bulb_c[0]),
                    t::num::temp(spec.evidence.wet_bulb_c[1]),
                ))
                .size(10.0)
                .color(t::MUTED)
                .family(t::family_mono_med()),
            );
        });
        for line in v.out_of_range.iter() {
            ui.label(
                RichText::new(format!("• {line}"))
                    .size(10.0)
                    .color(t::AMBER),
            );
        }
        let _ = phone;
    });

    if reset {
        let (d, q, c, s, cy) = (
            spec.value_of("waterMassFlowKgS"),
            spec.value_of("hotWaterC"),
            spec.value_of("targetColdWaterC"),
            spec.value_of("wetBulbC"),
            spec.value_of("dryBulbC"),
        );
        // The reset restores the *engine's* recorded pair, not the brief's 1000 kg/m3 conversion of it:
        // `waterFlowM3Hr` is the engine's own input field and the recorded value is 724.81 m3/hr (the two
        // conventions differ by 0.7 %, and the panel prints both).
        let _ = d;
        let flow = spec.psychro.recorded_water_flow_m3_hr;
        draft.0.duty = Duty {
            water_flow_m3_hr: flow,
            hot_water_c: q.unwrap_or(duty.hot_water_c),
            target_cold_water_c: c.unwrap_or(duty.target_cold_water_c),
            wet_bulb_c: s.unwrap_or(duty.wet_bulb_c),
            dry_bulb_c: cy.unwrap_or(duty.dry_bulb_c),
            pressure_pa: spec.value_of("pressurePa").unwrap_or(duty.pressure_pa),
            salinity_g_kg: spec.value_of("salinityGKg").unwrap_or(duty.salinity_g_kg),
            water_quality_class: spec.water_quality_class.clone(),
            cycles_of_concentration: spec
                .value_of("cyclesOfConcentration")
                .unwrap_or(duty.cycles_of_concentration),
        };
        vis.flash = Some(Flash {
            ok: true,
            text: "duty reset to the recorded design values".into(),
        });
    }
}

/// One editable row: the plain label, the engine's own field name, the value control and the unit. Round 5:
/// the row measures itself and puts the value + unit on a second line when the label and the control cannot
/// share one - a two-value row wraps to two lines before it clips.
#[allow(clippy::too_many_arguments)]
fn edit_row(
    ui: &mut egui::Ui,
    clip: &mut ClipProbe,
    id: &str,
    label: &str,
    engine_key: &str,
    unit: &str,
    value: &mut f64,
    hits: &mut HitMap,
    key: &str,
    speed: f64,
) -> bool {
    // Issue #137: the row is named in engineering words only. The input key (`hotWaterC`) stays the row's
    // machine identity - the clip-probe id and the project file - and is never painted next to the label.
    let _ = engine_key;
    let text = label.to_string();
    let avail = ui.available_width();
    let cell_w = 96.0;
    let unit_w = if unit == "-" {
        0.0
    } else {
        measure_ui(ui, unit, 9.5, t::family_mono_med())
    };
    let need = measure_ui(ui, &text, 10.5, egui::FontFamily::Proportional) + cell_w + unit_w + 22.0;
    let wrap = need > avail;
    let mut changed = false;
    let value_row = |ui: &mut egui::Ui, hits: &mut HitMap, value: &mut f64| {
        let mut changed = false;
        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
            if unit != "-" {
                ui.label(
                    RichText::new(unit)
                        .size(9.5)
                        .color(t::MUTED)
                        .family(t::family_mono_med()),
                );
            }
            let r = ui.add_sized(
                egui::vec2(cell_w, 20.0),
                egui::DragValue::new(value)
                    .speed(speed)
                    .max_decimals(2)
                    .fixed_decimals(if unit == "Pa" || unit == "g/kg" { 0 } else { 1 }),
            );
            if !key.is_empty() {
                hits.0.push((
                    key.to_string(),
                    [r.rect.min.x, r.rect.min.y, r.rect.width(), r.rect.height()],
                ));
            }
            changed = r.changed();
        });
        changed
    };
    let mut rect = ui
        .horizontal(|ui| {
            ui.label(RichText::new(&text).size(10.5).color(t::MUTED));
            if !wrap {
                changed = value_row(ui, hits, value);
            }
        })
        .response
        .rect;
    if wrap {
        let r2 = ui
            .horizontal(|ui| {
                changed = value_row(ui, hits, value);
            })
            .response
            .rect;
        rect = rect.union(r2);
    }
    clip.push(
        format!("panel.{id}"),
        if unit == "-" {
            text.clone()
        } else {
            format!("{text}  <{unit}>")
        },
        rect,
        avail,
        need,
        if wrap { 2 } else { 1 },
    );
    changed
}

/// Two editable rows side by side while the column can hold both cells, stacked when it cannot. (Round 4
/// used two fixed 162 px cells: at a 344 px column the pair was 330 px inside a 304 px content box, so the
/// second value's own control sat past the clip edge - the owner's "second value/unit off the edge".)
fn edit_pair(
    ui: &mut egui::Ui,
    hits: &mut HitMap,
    clip: &mut ClipProbe,
    id: &str,
    pair: [(&str, &str, f64, &str, f64, usize); 2],
) -> (f64, f64) {
    let avail = ui.available_width();
    let cell_w = 162.0;
    let side = avail >= cell_w * 2.0 + 8.0;
    let w = if side { cell_w } else { avail };
    let mut out = [pair[0].2, pair[1].2];
    // One cell, drawn once - side by side while the column can hold both, one per row when it cannot.
    #[allow(clippy::too_many_arguments)]
    fn cell(
        ui: &mut egui::Ui,
        hits: &mut HitMap,
        w: f32,
        label: &str,
        key: &str,
        speed: f64,
        decimals: usize,
        out: &mut f64,
    ) -> egui::Rect {
        ui.allocate_ui_with_layout(
            egui::vec2(w, 22.0),
            egui::Layout::left_to_right(egui::Align::Center),
            |ui| {
                ui.label(RichText::new(label).size(10.0).color(t::MUTED));
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let resp = ui.add_sized(
                        egui::vec2(58.0, 19.0),
                        egui::DragValue::new(out)
                            .speed(speed)
                            .fixed_decimals(decimals),
                    );
                    hits.0.push((
                        key.to_string(),
                        [
                            resp.rect.min.x,
                            resp.rect.min.y,
                            resp.rect.width(),
                            resp.rect.height(),
                        ],
                    ));
                });
            },
        )
        .response
        .rect
    }
    let mut rect;
    if side {
        rect = ui
            .horizontal(|ui| {
                let mut r = egui::Rect::NOTHING;
                for i in 0..2 {
                    let c = pair[i];
                    let rr = cell(ui, hits, w, c.0, c.1, c.4, c.5, &mut out[i]);
                    r = r.union(rr);
                }
                r
            })
            .inner;
    } else {
        let c0 = pair[0];
        rect = ui
            .horizontal(|ui| cell(ui, hits, w, c0.0, c0.1, c0.4, c0.5, &mut out[0]))
            .inner;
        let c1 = pair[1];
        let r1 = ui
            .horizontal(|ui| cell(ui, hits, w, c1.0, c1.1, c1.4, c1.5, &mut out[1]))
            .inner;
        rect = rect.union(r1);
    }
    let text = format!("{} / {}  <{}>", pair[0].0, pair[1].0, pair[0].3);
    clip.push(
        format!("panel.{id}"),
        text.clone(),
        rect,
        avail,
        measure_ui(ui, &text, 10.0, egui::FontFamily::Proportional) + 120.0,
        if side { 1 } else { 2 },
    );
    (out[0], out[1])
}

/// A read-only row (a derived value the panel only shows). Round 5: same self-measuring rule as `edit_row`.
fn ro_row(
    ui: &mut egui::Ui,
    clip: &mut ClipProbe,
    id: &str,
    label: &str,
    value: &str,
    unit: &str,
    hot: bool,
) {
    let avail = ui.available_width();
    let unit_w = if unit == "-" {
        0.0
    } else {
        measure_ui(ui, unit, 9.5, t::family_mono_med())
    };
    let need = measure_ui(ui, label, 11.5, egui::FontFamily::Proportional)
        + measure_ui(ui, value, 12.0, t::family_mono_med())
        + unit_w
        + 18.0;
    let wrap = need > avail;
    let mut rect = ui
        .horizontal(|ui| {
            ui.label(RichText::new(label).size(11.5).color(t::MUTED));
            if !wrap {
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    if unit != "-" {
                        ui.label(
                            RichText::new(unit)
                                .size(9.5)
                                .color(t::MUTED)
                                .family(t::family_mono_med()),
                        );
                    }
                    ui.label(
                        RichText::new(value)
                            .size(12.0)
                            .color(if hot { t::PRIMARY } else { t::INK })
                            .family(t::family_mono_med()),
                    );
                });
            }
        })
        .response
        .rect;
    if wrap {
        let r2 = ui
            .horizontal(|ui| {
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    if unit != "-" {
                        ui.label(
                            RichText::new(unit)
                                .size(9.5)
                                .color(t::MUTED)
                                .family(t::family_mono_med()),
                        );
                    }
                    ui.label(
                        RichText::new(value)
                            .size(12.0)
                            .color(if hot { t::PRIMARY } else { t::INK })
                            .family(t::family_mono_med()),
                    );
                });
            })
            .response
            .rect;
        rect = rect.union(r2);
    }
    clip.push(
        format!("panel.{id}"),
        format!("{label} {value} {unit}"),
        rect,
        avail,
        need,
        if wrap { 2 } else { 1 },
    );
}

/// The duty's own derived pair (range / approach), as a two-cell strip: read-only, live, and near the rows
/// it is computed from rather than below the fold of a scrolling form. Round 5: each cell is two lines
/// (label + value, then the arithmetic it is), so the strip fits the column at either width and no cell
/// needs a fixed minimum width that the column cannot honour.
fn derived_strip(
    ui: &mut egui::Ui,
    duty: &cockpit::engine::Duty,
    hits: &mut HitMap,
    clip: &mut ClipProbe,
) {
    let range = duty.hot_water_c - duty.target_cold_water_c;
    let approach = duty.target_cold_water_c - duty.wet_bulb_c;
    let avail = ui.available_width();
    let cells = [
        (
            "range",
            format!("{range:.2}"),
            "K · hot - target cold",
            "duty:range",
        ),
        (
            "approach",
            format!("{approach:.2}"),
            "K · target cold - wet bulb",
            "duty:approach",
        ),
    ];
    let cell_w = 158.0;
    let side = avail >= cell_w * 2.0 + 8.0;
    let w = if side { cell_w } else { avail };
    fn draw(
        ui: &mut egui::Ui,
        hits: &mut HitMap,
        w: f32,
        r: (&str, &str, &str, &str),
    ) -> egui::Rect {
        let frame = t::chip_frame(t::PANEL, t::LINE_SOFT).show(ui, |ui| {
            ui.set_min_width(w - 14.0);
            ui.vertical(|ui| {
                ui.horizontal(|ui| {
                    ui.label(
                        RichText::new(r.0.to_uppercase())
                            .size(8.5)
                            .color(t::MUTED)
                            .family(t::family_semi())
                            .extra_letter_spacing(0.6),
                    );
                    ui.label(
                        RichText::new(r.1)
                            .size(13.0)
                            .color(t::INK)
                            .family(t::family_mono_med()),
                    );
                    ui.label(RichText::new("K").size(9.5).color(t::MUTED));
                });
                ui.label(RichText::new(r.2).size(8.5).color(t::MUTED));
            });
        });
        let rect = frame.response.rect;
        hits.0.push((
            r.3.to_string(),
            [rect.min.x, rect.min.y, rect.width(), rect.height()],
        ));
        rect
    }
    let one = |i: usize| -> (&str, &str, &str, &str) {
        (cells[i].0, cells[i].1.as_str(), cells[i].2, cells[i].3)
    };
    let mut rect;
    if side {
        rect = ui
            .horizontal(|ui| {
                let mut r = egui::Rect::NOTHING;
                for i in 0..2 {
                    r = r.union(draw(ui, hits, w, one(i)));
                }
                r
            })
            .inner;
    } else {
        rect = ui.horizontal(|ui| draw(ui, hits, w, one(0))).inner;
        rect = rect.union(ui.horizontal(|ui| draw(ui, hits, w, one(1))).inner);
    }
    {
        // Each cell is a two-line block; its natural width is its wider line plus the chip's own padding.
        let cell_need = |i: usize| -> f32 {
            let head = format!("{} {}", cells[i].0.to_uppercase(), cells[i].1);
            measure_ui(ui, &head, 10.5, egui::FontFamily::Proportional).max(measure_ui(
                ui,
                cells[i].2,
                8.5,
                egui::FontFamily::Proportional,
            )) + 24.0
        };
        clip.push(
            "panel.duty.derived",
            format!(
                "{} · {}",
                cells[0].0.to_uppercase(),
                cells[1].0.to_uppercase()
            ),
            rect,
            avail,
            cell_need(0) + cell_need(1) + 10.0,
            if side { 1 } else { 2 },
        );
    }
}

fn chip(ui: &mut egui::Ui, text: &str, fg: egui::Color32) {
    t::chip_frame(t::PANEL, t::with_alpha(fg, 140)).show(ui, |ui| {
        ui.label(
            RichText::new(text)
                .size(9.5)
                .color(fg)
                .family(t::family_semi()),
        );
    });
}

fn hit(hits: &mut HitMap, key: &str, resp: egui::Response) -> egui::Response {
    let r = resp.rect;
    hits.0
        .push((key.to_string(), [r.min.x, r.min.y, r.width(), r.height()]));
    resp
}

/// A read-out row that is gated by the evidence rule: the number when the fixture can evidence it, the
/// amber `out of fixture range` when it cannot. Used by every duty-derived row in the read-out.
///
/// Round 5: it measures itself like the panel's own rows (a label plus a value plus its unit on one line,
/// or the value and unit on a second line), and it counts itself in the layout info: `read-out rows` must
/// equal `read-out units` whenever the duty is inside the recorded sweep, because every value keeps its
/// unit.
#[allow(clippy::too_many_arguments)]
pub fn gated_kv(
    ui: &mut egui::Ui,
    id: &str,
    label: &str,
    value: &str,
    unit: &str,
    gated: bool,
    hot: bool,
    clip: &mut ClipProbe,
    info: &mut LayoutInfo,
) {
    let avail = ui.available_width();
    let shown = if gated { OUT_OF_FIXTURE_RANGE } else { value };
    let unit_w = if gated || unit.is_empty() {
        0.0
    } else {
        measure_ui(ui, unit, 10.0, t::family_mono_med())
    };
    let need = measure_ui(ui, label, 11.5, egui::FontFamily::Proportional)
        + measure_ui(ui, shown, 12.5, t::family_mono_med())
        + unit_w
        + 18.0;
    let wrap = need > avail;
    let draw = |ui: &mut egui::Ui, with_label: bool| {
        ui.horizontal(|ui| {
            if with_label {
                ui.label(RichText::new(label).size(11.5).color(t::MUTED));
            }
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                if gated {
                    ui.label(out_of_range_text());
                } else {
                    if !unit.is_empty() {
                        ui.label(
                            RichText::new(unit)
                                .size(10.0)
                                .color(t::MUTED)
                                .family(t::family_mono_med()),
                        );
                    }
                    ui.label(
                        RichText::new(value)
                            .size(12.5)
                            .color(if hot { t::PRIMARY } else { t::INK })
                            .family(t::family_mono_med()),
                    );
                }
            });
        })
    };
    let mut rect = draw(ui, true).response.rect;
    if wrap {
        let r2 = draw(ui, false).response.rect;
        rect = rect.union(r2);
    }
    // An empty label is a layout spacer (the water-quality header row uses one); it is not a read-out row.
    if !label.is_empty() {
        info.readout_rows += 1;
        if !gated && !unit.is_empty() {
            info.readout_units += 1;
        }
    }
    clip.push(
        format!("readout.{id}"),
        format!("{label} {shown} {unit}"),
        rect,
        avail,
        need,
        if wrap { 2 } else { 1 },
    );
}

/// The panel's own pre-check: the physical limits it names before the engine is asked. Empty when the duty
/// passes. (The engine's own `EngineOutput.validation` is printed beside these and is the authoritative one.)
pub fn precheck(duty: &Duty) -> Vec<String> {
    let mut pre: Vec<String> = Vec::new();
    let approach = duty.target_cold_water_c - duty.wet_bulb_c;
    if approach < m::APPROACH_MARGIN_MIN_C {
        // issue #137: the house format (0.1 °C / K, U+2212 minus); the approach is the one figure the
        // limit turns on, so it keeps two decimals - 0.20 K and 0.2 K say the same, 0.49 K must not read 0.5
        pre.push(format!(
            "cold water must exceed the entering wet bulb by at least {} K: target {} °C − wet bulb {} °C = {:.2} K",
            t::num::kelvin(m::APPROACH_MARGIN_MIN_C),
            t::num::temp(duty.target_cold_water_c),
            t::num::temp(duty.wet_bulb_c),
            approach
        ));
    }
    if duty.hot_water_c <= duty.target_cold_water_c {
        pre.push(format!(
            "hot water must exceed the target cold water: {} °C vs {} °C",
            t::num::temp(duty.hot_water_c),
            t::num::temp(duty.target_cold_water_c)
        ));
    }
    if duty.water_flow_m3_hr <= 0.0 {
        pre.push("water flow must be positive".to_string());
    }
    pre
}

/// The `data-duty-*` markers the frames read.
pub fn markers(res: &DutyRes, duty: &Duty) -> (String, String, String) {
    match verdict(res, duty) {
        Some(v) => (
            if v.in_range() {
                "in-range"
            } else {
                "out-of-fixture-range"
            }
            .to_string(),
            v.out_of_range.join(" | "),
            match res.spec.as_ref() {
                Some(s) => format!(
                    "{:.1},{:.1}",
                    s.evidence.water_flow_m3_hr[0], s.evidence.water_flow_m3_hr[1]
                ),
                None => String::new(),
            },
        ),
        None => ("no-spec".to_string(), String::new(), String::new()),
    }
}

/// The two derived duty quantities, for the panel and the mirror.
pub fn derived(duty: &Duty) -> (f64, f64) {
    (
        duty.hot_water_c - duty.target_cold_water_c,
        duty.target_cold_water_c - duty.wet_bulb_c,
    )
}
